### ISSUE TITLE
multiple project support

### ISSUE THREAD

**Issue by jdegoes** [purescript-contrib/pulp#10]
A place for me to track thoughts on supporting multiple projects.

Simple project:

```
src/
test/
bower.json
```

Multiple projects:

```
project1/
project1/src/
project1/test/
project1/bower.json

project2/
project2/src/
project2/test/
project2/bower.json
```

A subproject A depends on a subproject B by referencing `"B": "../B"` in its bower file (need to test to make sure this works, seems like it's supported).

Outstanding issues:
1. How to handle the fact that each subproject has its own main function? Define pulp.json or something else?
2. Do all the core commands scale to multiple projects?

Probably other stuff.

**Comment by hdgarrood** [comment]
Housekeeping: there doesn't seem to be much demand for this, and nothing has happened for a long time, so I'm going to close this.
