### ISSUE TITLE
Proposal for --override-src build option

### ISSUE THREAD

**Issue by ethul** [purescript-contrib/pulp#100]
I have a project where I have both purescript files and FFI JS files, but also other non-FFI JS files in the `src` directory. `pulp` by default uses the glob patterns `"src/**/*.purs"` and `"src/**/*.js"`, which includes both the FFI and non-FFI JS src files.

I am thinking it would be handy to have an option `--override-src` or something that would allow for a different source path to be passed in. For example `--override-src src/purescript` would yield the glob patterns `"src/purescript/**/*.purs"` and `"src/purescript/**/*.js"`.

Is there interest in a PR for such an option?

**Comment by bodil** [comment]
I think that'd be useful. You could probably just call it `--src` though, and while you're at it you'll probably want to add a corresponding `--test` option.

**Comment by bodil** [comment]
...or, come to think of it, perhaps something like `--src-path` would be less ambiguous.

**Comment by ethul** [comment]
Great! `--src-path` sounds good. And I was planning on one for test as well. I will add `--test-path` for that. Any preference on a short switch? Maybe there should not be one?

**Comment by bodil** [comment]
Yeah, I think these shouldn't need a short version.

**Comment by ethul** [comment]
Agreed. Thanks!

**Comment by paf31** [comment]
:+1: but would it make sense to override the whole glob instead of just the prefix? Maybe someone wants to use Pulp but not Bower for example, and manage their own dependencies. Same thing for tests, since you might have multiple test suites.

**Comment by ttbodil** [comment]
I'd make those a separate option, because they lead to a lot more typing and potential for error, but I agree they'd be useful too.
