### ISSUE TITLE
Running build more than once doesn't rebuild

### ISSUE THREAD

**Issue by nicolashery** [purescript-contrib/pulp#105]
Using: https://github.com/bodil/pulp/commit/a7af148f0cda9c5cdca375ee47947d5cd1cb42ae (5.0)

Reproduce:

``` bash
$ pulp -w build
* Building project in [...]
psc: No files found using pattern: src/**/*.js
* Build successful.
# Change an existing .purs file
* Source tree changed; restarting:
* Project unchanged; skipping build step.
```

Expected: 

``` bash
$ pulp -w build
* Building project in [...]
psc: No files found using pattern: src/**/*.js
* Build successful.
# Change an existing .purs file
* Source tree changed; restarting:
* Building project in [...]
psc: No files found using pattern: src/**/*.js
* Build successful.
```

**Comment by maddie927** [comment]
Also running into this.  It seems to be an issue with noticing that files have changed rather than a `pulp -w` issue, as the same thing happens when I run `pulp build` twice.  Here's the command I'm using, in case the param is relevant: `pulp build --src-path src/purs`.

For now I'm working around this with `--force` (this command works fine with `-w` too): `pulp build --force --src-path src/purs`

**Comment by ttbodil** [comment]
Which OS are you both on, just for the record? And which file system?

**Comment by nicolashery** [comment]
OS X 10.10.5 (Yosemite), default file system

**Comment by maddie927** [comment]
OS X 10.11.1, also default file system (the disk utility calls it "OS X Extended", and it's not case-sensitive)

**Comment by maddie927** [comment]
I have an Ubuntu system at home, so if there's no update by tonight I'll try it there too.

**Comment by nicolashery** [comment]
I think I found the culprit. Pulp is checking the directory's `mtime`, but modifying a file inside the directory doesn't change the directory's `mtime` (at least not on OS X). Example:

``` bash
$ touch src

$ date -j -f "%s" "$(stat -f "%m" src)" +"%Y/%m/%d %T"
2015/11/24 15:09:46

$ touch src/Foo.purs

$ date -j -f "%s" "$(stat -f "%m" src/Foo.purs)" +"%Y/%m/%d %T"
2015/11/24 15:10:31

$ date -j -f "%s" "$(stat -f "%m" src)" +"%Y/%m/%d %T"
2015/11/24 15:09:46
```

We may need to walk the directory? Don't know if that has any performance concerns?

**Comment by maddie927** [comment]
Hmm..   Timestamps seem unreliable, even on a per-file basis.  Does checking out source code saved on someone else's computer have their timestamps or the time you checked out the code?  I'd think you'd want to check the files `mtime` or hash it and cache that for each file specifically to know if things have changed.

`src`: just source files
`output`: just compiled code
`.pulp-cache/?`: a tree matching src with a hash for each file

Any trees where the hashes diff get rebuilt.

**Comment by maddie927** [comment]
Timestamps _might_ be enough for a watch-based command, provided it always began with a forced rebuild.

**Comment by bodil** [comment]
Sigh, I suspected there was a filesystem issue at the heart of this. It seemed to work for me because on ext4 a directory's mtime will get bumped when one of its children does. So I guess we'll have to scan the entire tree...

Hashing is definitely not an option, that's too slow.

**Comment by maddie927** [comment]
Yeah, finding that as well : ]
Right now I'm playing with a hash of all the mtimes of a directory's files. It seems ok but I have to test a larger project.

**Comment by bodil** [comment]
Just finding the max mtime of all children should be enough, I'd think?

**Comment by hdgarrood** [comment]
Sorry if this is obvious, but it is necessary to check modification times? I thought `psc` did that already?

**Comment by hdgarrood** [comment]
Oh of course, because it's not just `psc`, we might also be calling `psc-bundle` or `browserify`, which might also take a while. Ok. In that case, maybe in the case where `psc` doesn't have to do anything, we want it to be able to report this somehow? And then pulp would call `psc` every time, but only continue with `psc-bundle` or `browserify` or whatever in the case where `psc` had to change something.

**Comment by garyb** [comment]
@hdgarrood `psc` does check the modification dates of the inputs to determine if anything has changed, yes.

**Comment by bodil** [comment]
`psc-bundle` certainly doesn't. One mtime check is also faster than spawning the `psc` process, though it remains to see if scanning the whole tree for max mtime is...

**Comment by garyb** [comment]
Yeah I `psc-bundle` just does it's thing every time, and even the check in `psc` isn't super reliable it seems...

**Comment by bodil** [comment]
Running a recursive scan of the pulp source tree to find the highest mtime takes nearly one second. That's horrendously slow. :(

Is there any way we can tell if `psc` found any changes, and skip further processing if it did? I can't think of any beyond doing a max mtime scan of the output directory, which would also be a bit slow.
