### ISSUE TITLE
pulp init can't find bower

### ISSUE THREAD

**Issue by LukaHorvat** [purescript-contrib/pulp#108]
This is probably the same as #68 but that issue got closed.

Anyways, this is a fresh install of purescript, node/npm, bower and pulp.

This is the output

```
C:\Users\Luka\Documents\Projects\SM>pulp init
* Generating project skeleton in C:\Users\Luka\Documents\Projects\SM
* ERROR: `C:\Users\Luka\AppData\Roaming\npm\node_modules\pulp\node_modules\bower\bin\bower` executable not found. (nor `C:\Users\Luka\AppData\Roaming\npm\node_modules\pulp\node_modules\bower\bin\bower.cmd`)
```

There is a bower file in that directory but it's JS without an extension.

**Comment by bodil** [comment]
So the first file it's complaining about missing actually exists?

**Comment by LukaHorvat** [comment]
Yeah, it's there. But it isn't executable because it's an extensionless JavaScript file.

**Comment by hdgarrood** [comment]
How about we address this by launching the `node` executable and provide the path to the `bower` bin file as the first argument, and then all the rest afterwards? I've just implemented this in the purescript branch: https://github.com/bodil/pulp/commit/3cfacb5af6bea849ea046bd403ceddd666e6bd35

It works for me on my Windows VM as well as my main Ubuntu machine.

**Comment by bodil** [comment]
Yes, that ought to work everywhere.
