### ISSUE TITLE
Option to clear screen (--clear) when using --watch

### ISSUE THREAD

**Issue by wavebeem** [purescript-contrib/pulp#116]
It would be really nice to have an option that cleared the screen when using `--watch` so that the relevant info was at the top of your terminal.

**Comment by hdgarrood** [comment]
Does `pulp --watch --then clear build` work?

**Comment by wavebeem** [comment]
No, because that clears **after** compilation, so you can't read any of the output. It needs to happen **before** a new compilation is initiated.

Also, I think most people would probably benefit from having this on by default, with an option to turn it off if you want the old behavior.

**Comment by ttbodil** [comment]
That would definitely be a nice thing to have. Not sure I'd want it to be on by default, though. I generally prefer as many things as possible to be off by default; less surprises that way.

**Comment by damncabbage** [comment]
I had a crack at this in the just-referenced #135 pull request. I implemented a generic `--before` option instead, with a README suggestion of `pulp --before clear --watch build`, or some other command that's appropriate for the platform (like `cls`). Any thoughts?

**Comment by bodil** [comment]
Seems legit, guess we can resolve this one. :)
