### ISSUE TITLE
Rename --optimise?

### ISSUE THREAD

**Issue by hdgarrood** [purescript-contrib/pulp#117]
If `psc` ever gets options which control optimisations, the pulp option --optimise would probably become a little confusing. And perhaps --dead-code-elimination or maybe --dce would describe it better anyway?

**Comment by bodil** [comment]
idk, I like the `-O`, it's got a familiar feel. Defer this until there are other compiler flags? I could see it enabling a set of default optimisations even then.

**Comment by hdgarrood** [comment]
Yeah, sounds sensible.
