### ISSUE TITLE
test subcommand should not accept --optimise

### ISSUE THREAD

**Issue by hdgarrood** [purescript-contrib/pulp#124]
If you run `pulp test -O`, you get the output of psc-bundle dumped to your terminal just before the test output, which is a bit strange. I don't think there's any need for `test` to have the --optimise option at all, given that it only operates on the output of `psc` directly in the `output` directory.

**Comment by damncabbage** [comment]
Should the `-O` also be excluded for `pulp server`? (As it is, it doesn't have access to `--to`, like `pulp test`).

**Comment by bodil** [comment]
Yes, `-O` shouldn't have been an option for either of those.
