### ISSUE TITLE
No need for postinstall script

### ISSUE THREAD

**Issue by hdgarrood** [purescript-contrib/pulp#127]
I just realised that `postinstall` scripts get run not only after you `npm install` in the project directory for development, but also when you actually install pulp, ie, with `npm install -g pulp`. There's no need for us to be running `bower install` in the second case, since all the purescript dependencies have already been bundled up with `psc-bundle`. And I imagine that this could cause problems if a solution for dependencies can't be found. So we should probably get rid of that?

Do you know of an alternative which works similarly, but only gets run in the case where you run `npm install` in the project directory (ie, in the same situation where `devDependencies` would be installed)?

**Comment by bodil** [comment]
Ah, yes, that's true. I believe the postinistall hook is entirely redundant, as the `bower install` is also happening in the prepublish hook, which is where this is supposed to be done. That's also the hook you're looking for, btw. :)

**Comment by hdgarrood** [comment]
Cool - I'll send a PR. :)
