### ISSUE TITLE
Add --skip-entry-point flag for pulp build --to

### ISSUE THREAD

**Issue by hdgarrood** [purescript-contrib/pulp#130]
As long as `--to` is specified, I think a `--skip-entry-point` flag for `pulp build` would make sense. currently we only have one for `pulp browserify`.

We can achieve this simply by omitting the `--main` option to `psc-bundle`, I think.

**Comment by damncabbage** [comment]
I had a crack at making this change (https://github.com/bodil/pulp/compare/master...damncabbage:topic/skip-entry-for-to), but I have no idea how you'd actually consume this file, except by maybe dumping it onto a page and accessing things via the `PS` global.

What was the use-case for this? (I can't see one outside of the already-implemented `browserify` case.)

**Comment by hdgarrood** [comment]
Right, dumping it onto a page and accessing via the PS global was the initial plan.

I think there was also someone in IRC who wanted to just append exports = PS to the bottom and use it as a node module.

I think if we don't want pulp build --skip-entry-point because it's redundant, surely we could use the same argument to ditch pulp build --to as well? I'd rather keep both; the output of psc-bundle is certainly easier to understand if you want to fiddle with things, such as the appending exports = PS example.

**Comment by bodil** [comment]
I'd rather not add too much specialised behaviour - `--skip-entry-point` is fair enough, that's just disabling a sensible default, but once that's there it's trivial for users with this particular need to append eg. the `exports = PS;` line to the output on their own.

**Comment by hdgarrood** [comment]
Oh absolutely agreed, I was thinking that the appending would be done outside pulp too.

**Comment by damncabbage** [comment]
This can be closed (#137 has been merged).
