### ISSUE TITLE
Document how pass-through options are used

### ISSUE THREAD

**Issue by hdgarrood** [purescript-contrib/pulp#140]
I don't think every command passes the remainder of options through to `psc`. I think we should add a `String` field to the `Command` type which explains what, if anything, happens to extra options, and then display that at the bottom of `pulp <cmd> --help`. We should also update the README if we do this.

**Comment by bodil** [comment]
Might be smart. Commands pass the args on to the most "obvious" child process, which may not necessarily be all that obvious.
