### ISSUE TITLE
--runtime/-r option no longer working?

### ISSUE THREAD

**Issue by paf31** [purescript-contrib/pulp#143]
I used to use this with `-r cat` when running tests to output the test JS to a file, but it doesn't seem to do anything any more.

**Comment by hdgarrood** [comment]
Can you give the whole command you're using please?

**Comment by paf31** [comment]
`pulp test -r cat > index.js`

**Comment by hdgarrood** [comment]
I'm not entirely sure how we've got here, but there is an `engine` option now. Does using `--engine cat` instead do what you want? I think we should probably remove one of `--engine` or `--runtime`; they do the same thing, as far as I can tell. Also I looked in the source, and the `--runtime` option does indeed seem to be ignored.

**Comment by bodil** [comment]
`--runtime` sounds more correct to me than `--engine`. Let's standardise on it? It'll be a breaking change either way.

**Comment by hdgarrood** [comment]
Ok, sounds good to me.

**Comment by hdgarrood** [comment]
I'll send a PR in a minute.
