### ISSUE TITLE
Colours disappear when redirecting output

### ISSUE THREAD

**Issue by hdgarrood** [purescript-contrib/pulp#147]
The log messages with coloured bullets lose their colours when output is redirected, eg

```
$ pulp browserify > app.js
```

I think this is because we are checking `stdout.isTTY`. We should be checking `stderr` instead.

**Comment by ttbodil** [comment]
Isn't this expected behaviour, though?

**Comment by hdgarrood** [comment]
It's not what I would have expected, especially given that all of pulp's logging goes to stderr.

**Comment by ttbodil** [comment]
Ah, you mean the log messages printed to the unredirected stderr when you redirect stdout? Yes, that's definitely not right.

**Comment by hdgarrood** [comment]
Yes, that's what I meant. :)

**Comment by hdgarrood** [comment]
And, I've just realised, the log messages printed to stderr include the colour escape codes in the case where you don't redirect stdout, even if stderr is redirected to a file or something! We should make sure we fix that too.
