### ISSUE TITLE
pulp --help results in error

### ISSUE THREAD

**Issue by natefaubion** [purescript-contrib/pulp#148]
```
$ pulp --help
* ERROR: Property 'parse' of object #<Object> is not a function
```

6.2.1

**Comment by hdgarrood** [comment]
:scream:

Works on my machine, so I'm not sure what's gone wrong here. Does the same thing happen if you create a new directory and install a new copy of Pulp into it? Also, could you try to get a stack trace? The easiest way, I think, would be to modify `pulp.js` inside your `node_modules`. If you look for this bit:

```
  var failed = function (err) {
      return function __do() {
          Control_Monad_Eff_Console.error("* ERROR: " + Control_Monad_Eff_Exception.message(err))();
          return Node_Process.exit(1)();
      };
  };
```

and add an extra line just before `Node_Process.exit(1)()`, that should do it.

**Comment by hdgarrood** [comment]
(I realise this is a bit silly. I think we should add a `--trace` flag for this situation.)

**Comment by natefaubion** [comment]
I think this is a node version issue. We should probably put the node version in package.json.

**Comment by hdgarrood** [comment]
As in, your version of node is incompatible with Pulp? What version is it?

**Comment by natefaubion** [comment]
Its old, I forgot to switch to latest from working on an old project. It's due to the built in path module not having a `parse` function.
