### ISSUE TITLE
Check node is >= 4 at startup

### ISSUE THREAD

**Issue by hdgarrood** [purescript-contrib/pulp#150]
And exit with a helpful error, if so. See also: #148

**Comment by ttbodil** [comment]
Just adding an `engines` field to `package.json` should work?

**Comment by hdgarrood** [comment]
Didn't know about that field :)

I think we should probably do both, given that the default behaviour of `engines` seems to only be to warn if your version of node is unsupported: https://docs.npmjs.com/misc/config#engine-strict
