### ISSUE TITLE
Configurable psc executables

### ISSUE THREAD

**Issue by natefaubion** [purescript-contrib/pulp#157]
Either by flag or by env, I'm open to either. In https://github.com/natefaubion/purescript-psa I use a flag, but an env var might be better for pulp because it already has lots of options.

**Comment by hdgarrood** [comment]
Having just tried `psa` out, I think it should be Pulp's default. Pulp's all about sensible defaults, right? :)

It doesn't seem particularly likely to me that another `psc` frontend will appear, so I'm not sure if we even need to make this more generally configurable. Once `psc` 0.8 is out, I will probably want to use psa all the time, and I don't want to do anything like adding `export PULP_PSC_COMMAND="psa"` to my `.profile`, or adding `--psc-command=psa` to every package.json, and every direct command line pulp invocation. Is `psa` likely to change that often? I'm leaning towards including it as a library.

**Comment by bodil** [comment]
I'm just worried about surprising the user, whether it's a pleasant surprise or not. What if we defaulted to `psa` if it's on the path, and used `psc` if not?

Alternatively, I'm not strongly opposed to embedding psa in pulp, as long as it can be disabled with a command line option.

**Comment by passy** [comment]
> I'm just worried about surprising the user, whether it's a pleasant surprise or not. What if we defaulted to psa if it's on the path, and used psc if not?

:+1: to that. I guess a flag to opt out would still be useful to have in case you want the default output for bug reports or (god forbid) psa has a bug?

**Comment by hdgarrood** [comment]
Ok, using `psa` if it's there and `psc` otherwise sounds good to me. Also :+1: for @passy's suggestion.

**Comment by hdgarrood** [comment]
Fixed by 77a149ebf2b33c0953ce0e64d1837e5a6f15d41f?
