### ISSUE TITLE
Slow build with no changes without --force

### ISSUE THREAD

**Issue by nwolverson** [purescript-contrib/pulp#164]
Reliably (at least for this project? not tested extensively) my builds are super slow if I don't specify `--force` when there are no changes (it's also slow when there are changes but less obvious). Running the command anyway and letting `psc` find no changes is way quicker. 

System: OSX

```
$ pulp -v
Pulp version 7.0.0
psc version 0.8.0.0
```

Timings after a previous build already completed:

```
$ time pulp build 
* Project unchanged; skipping build step.

real    0m42.227s
user    0m24.573s
sys 0m19.674s
```

```
$ time pulp build --force
* Building project in /Users/nicholaw/git/atom-ide-purescript
* Build successful.

real    0m1.295s
user    0m3.224s
sys 0m0.533s
```

**Comment by hdgarrood** [comment]
Can you test with 5.0.2 (i.e. the last version of pulp that was JS) and see if that's any faster? Also, how many files are there in all your purescript source directories, including `bower_components`? Pulp looks through all the source directories fo see if anything has changed, so that's probably what's causing the slowness, I think.

**Comment by hdgarrood** [comment]
Whatever this turns out to be, though, this might be another reason to simply get rid of the build-skipping stuff. (See also: #146)

**Comment by nwolverson** [comment]
Humm, on 5.0.2 it takes a few minutes then exits on out of memory (a little under 2G).

```
$ find {bower_components/,src/} -name *.purs | wc -l
     192
```

**Comment by hdgarrood** [comment]
That's strange: for me, running `pulp build` with no changes on Halogen is under 0.2s, with both psc 0.7.6.1 and 0.8.0.0. I'm using commit a896ef5 of Halogen, which currently lists 225 files for that same `find` command. Maybe something to do with OSX? Or are you doing anything weird with the filesystem, like symbolic links or something? It would be nice to know the cause, but at this stage, I'm tempted to say it's not worth the effort to diagnose, and we should just remove the build skipping stuff (`Pulp.Rebuild` and `Pulp.Mtime`).

**Comment by nwolverson** [comment]
Ahh. I had previously used `bower link`, on top of that I think the linked directory may have contained a dodgy symlink (outside of its `src/` directory). This all works fine and quickly when removing the linked dependency.

**Comment by hdgarrood** [comment]
Ok, cool. I had forgotten about bower link, but I think pulp should definitely support it - it can be incredibly useful.

**Comment by nwolverson** [comment]
For reference there is no issue when the `bower link`'d dependency does not have a stupid symlink in it which probably results in a cycle, that's my stupidity - happy to close this whatever happens. Though my expectation would have been that only files in the source glob would have been checked.

(I could imagine a situation where 2 projects have a bower link to each other due to some dev dependency thing, I think I've done it before, but I don't think it's worth caring too much about)

**Comment by hdgarrood** [comment]
I think that if `psc` can handle something, then `pulp` should probably be able to handle it as well. But it looks like we're getting rid of the build skipping stuff anyway.
