### ISSUE TITLE
Problems with psa + psc 0.7.x

### ISSUE THREAD

**Issue by hdgarrood** [purescript-contrib/pulp#166]
If you have `psc` <=0.8 on your PATH in addition to `psa`, `pulp build` on master now breaks with a less than helpful error message:

```
> pulp build
Usage: psc [FILE] [-f|--ffi ARG] [-o|--output ARG] [--no-tco] [--no-magic-do]
           [--no-opts] [-v|--verbose-errors] [-c|--comments]
           [-r|--require-path ARG] [-p|--no-prefix]
```

I think we need to do one of the following:
1. If `psa` is detected, ensure `psc` is at least 0.8 before continuing. If not, just use `psc`.
2. If `psa` is detected, ensure `psc` is at least 0.8 before continuing. If not, print an error and exit.
3. Refuse to run at all with `psc` <= 0.8.

I think I like 1) the best.

**Comment by natefaubion** [comment]
I can probably add this in. The question is how to propagate the version from `validate`. Should I just do it like you do in `addProject`?

**Comment by hdgarrood** [comment]
That's a bit gross, I think. Maybe this is an opportunity to refactor that and do all this a bit better. What if we had something like this:

``` purescript
type PulpEnv =
  { project :: Maybe Project
  , usePsa :: Boolean
  }
```

and then change Action to take one of these:

``` purescript
newtype Action = Action (Args -> PulpEnv -> AffN Unit)
```

So the `PulpEnv` (any better name suggestions are welcome) gets constructed after parsing arguments, but before actually doing anything. This approach would also make it easy to implement things like #149 by just adding extra fields to `PulpEnv`.

**Comment by hdgarrood** [comment]
Actually, for now, I think doing it like `addProject` should be fine. I'll try to do that refactoring later.

**Comment by natefaubion** [comment]
I can just do the check in main and override the `noPsa` option.

**Comment by hdgarrood** [comment]
Ah of course, that works.
