### ISSUE TITLE
Allow specifying paths to build tools

### ISSUE THREAD

**Issue by raymoo** [purescript-contrib/pulp#171]
If someone has multiple versions of purescript compiler and/or tools, they might want to use a specific one, instead of whatever is in their path.

**Comment by hdgarrood** [comment]
what if you invoke pulp like this?

```
$ PATH=/path/to/some/specific/psc:$PATH pulp build
```

**Comment by hdgarrood** [comment]
I don't see a reason why modifying `PATH` is insufficient, so I'm closing (but feel free to reopen if you disagree).
