### ISSUE TITLE
Allow changing the glob used for matching foreign files

### ISSUE THREAD

**Issue by raymoo** [purescript-contrib/pulp#172]
If a project has a non-javascript target, it may have foreign implementations with a different extension (e.g. look for `src/**/*.lua` rather than `src/**/*.js`)

EDIT: It looks like there is some similar discussion in #55

**Comment by hdgarrood** [comment]
I don't think #55 is relevant.

Also, at the moment, no alternative backends have really taken off yet, and there are still lots of unresolved questions around backends other than JS. We definitely want to address this issue at some point, but imo, now is not the time to do it.

**Comment by paf31** [comment]
I think it would be nice to be able to change any of the default globs used in Pulp, either with a config file, or with command line options. There are other reasons to want this - maybe I want to set up a global package database, for example.

I'll happily put a PR together if you think it'd be accepted.

**Comment by hdgarrood** [comment]
As of 0.9.x, the compiler uses a convention for locating FFI files, so there's no need for Pulp to do anything about this now.
