### ISSUE TITLE
Include Prelude in generated .psci file

### ISSUE THREAD

**Issue by Thimoteus** [purescript-contrib/pulp#178]
with a flag to disable, or the other way around: add a flag that appends some given list of imports into `.psci`.

**Comment by hdgarrood** [comment]
Pulp is supposed to preserve all commands in your .psci file other than :module and :foreign commands, which just specify which files to pick up, so I think you might be able to achieve this just by appending "import Prelude" yourself?

**Comment by Thimoteus** [comment]
Hmmm. I haven't been able to get this to work.

```
 > pulp --version
Pulp version 8.0.0
psc version 0.8.0.0 using /home/thimoteus/.psvm/current/bin/psc
```

I'll edit `.psci`, add in `import Prelude` to the bottom, then call `pulp psci` and that line is erased: I have to explicitly import Prelude from psci again.

edit: whoops, accidentally closed

**Comment by hdgarrood** [comment]
Ah, ok then.

The way I see it, we have a problem in that the .psci file has two separate functions. The first is to contain a list of all the files to be loaded by psci. The second is for any extra manual configuration (like what you are trying to do here). If we do want to support this kind of manual configuration, I'd like to separate these two things. One option would be for psci to accept file globs like psc, and then we could modify all the tools which currently produce .psci files to instead just invoke psci with some globs. This also removes a source of confusion, namely running psci when your .psci file is not quite up to date. However it does mean that you'd basically have to invoke psci via some external tool.

Alternatively I guess we could try (harder) to machine generate portions of .psci and leave the rest alone. This would be easier if we could use file globs in the :module and :foreign commands.

@paf31 @garyb any thoughts?

**Comment by hdgarrood** [comment]
.psci files are no longer a thing as of 0.9.x, so I'll close this.
