### ISSUE TITLE
Enhanced color customization options

### ISSUE THREAD

**Issue by fluffynukeit** [purescript-contrib/pulp#18]
Thanks for making this great tool!  It really makes the PS setup process painless.  I'm a relatively new user, but I don't think I'm ever going back to grunt...

One thing I'd like to see is greater customization in color options beyond the `--monochrome` flag.  I'm using the solarized shell color scheme, and the "green" asterisks for status messages show up as a gray slightly darker than the message text color, so the difference is minimal.  I'd like to be able to customize the colors to work around this.

I think a reasonable solution to this would be one or more additional command line flags to define:
1.  The color of the asterisks used for normal log messages.
2.  The color of the asterisks used for error log messages.
3.  An option to enable forcing the text of the message to match the color of the leading asterisk.  This would make the whole status message colored instead of just the leading asterisk.

I don't think it's necessary to have fine-grained control over what shade is used; being able to select from among a set of supported colors would be fine for me.  I would just choose the ones that worked best for my environment.

A nice-to-have on top of those is to capture and colorize messages from underlying tasks, so build error and runtime error text is shown in e.g. red and not just `* ERROR: Subcommand terminated with error code 8`.

Essentially, when I see a long list of build tasks printing to the screen, followed by program/test output, followed by errors, liberal use of color helps me to more easily identify the messages that are most important to me.  Thanks!

**Comment by hdgarrood** [comment]
If the green asterisks are difficult to see, then I think that's a problem with your terminal colour scheme, not pulp. Anyway, the relevant PR has been closed, so I think we can close this too for the same reason.
