### ISSUE TITLE
First command in pulp psci do nothing

### ISSUE THREAD

**Issue by user471** [purescript-contrib/pulp#181]
```
pulp init
pulp build
pulp psci
```

then I enter

```
:b Main
```

and nothing is happening
I use Windows.

**Comment by hdgarrood** [comment]
But subsequent commands do work? This might be specific to Windows, then, as it is working as intended for me (on Ubuntu).

**Comment by user471** [comment]
> But subsequent commands do work? 

Yes, the problem is only with first command. Also psci without pulp doesn't have this problem.

**Comment by hdgarrood** [comment]
This is quite old now, so I'm going to close it. If anyone sees this again, I think the most likely cause of this would be an out-of-date version of Node (I've seen a few issues of psci weirdness fixed by updating Node). If updating Node doesn't fix, please feel free to reopen / open new issues.
