### ISSUE TITLE
"import Prelude (Unit)" in new project leads to confusion

### ISSUE THREAD

**Issue by Bellarmine-Head** [purescript-contrib/pulp#187]
Newbie comment...

My first afternoon with PureScript and Pulp... I create new project with `pulp init`, and later amend `Main.purs` to do a simple string concatenation, more or less along the lines of the [Getting Started](http://www.purescript.org/learn/getting-started/) text.

The trouble is that the (++) operator isn't recognized:-

>  Unknown value (++)

After much head scratching I realize that I have to change the generated `import Prelude (Unit)` to `import Prelude`.

Maybe `Main.purs` in both `src` and `test` should be generated that way in the first place...?

**Comment by hdgarrood** [comment]
Firstly, thanks so much for reporting issues, it's really valuable to learn about issues that newcomers are facing :)

I think you're absolutely right, we should change that back to an open import.

**Comment by hdgarrood** [comment]
Fixed by #193.
