### ISSUE TITLE
`--modules` doesn't work when using `--skip-entry-point`

### ISSUE THREAD

**Issue by natefaubion** [purescript-contrib/pulp#188]
If you just `pulp init` a new project and add a file to `src/Foo.purs`

``` purescript
module Foo where
foo = "foo"
```

Then run `pulp build --optimise --modules Foo` it will get included. But if I add `--skip-entry-point`, it does not. If I run the corresponding `psc-bundle "output/**/*.js" -m Main -m Foo` the output is correct.

**Comment by hdgarrood** [comment]
Thanks for the report. I'll take a look when I get a moment.

**Comment by hdgarrood** [comment]
This one turned out to be a bit embarrassing. I think this might be the first time I've had a bug as a result of me and the compiler disagreeing about how to parse something!
