### ISSUE TITLE
`pulp build` does not work with psa: 

### ISSUE THREAD

**Issue by dszakallas** [purescript-contrib/pulp#194]
I want to get rid of the ~5000 lines of warning messages when I build [this](https://travis-ci.org/collection-benchmarks/collection-benchmarks-purescript). But I get error messages by using the `--censor-warnings` option: 

```
> pulp build -O --censor-warnings -o lib-gen

* Building project in /Users/david/Projects/collection-benchmarks-purescript
Invalid option `-o'

Usage: psc [FILE] [-f|--ffi ARG] [-o|--output ARG] [--no-tco] [--no-magic-do]
           [--no-opts] [-v|--verbose-errors] [-c|--comments]
           [-r|--require-path ARG] [--source-maps] [-p|--no-prefix]
           [--json-errors]
```

**Comment by hdgarrood** [comment]
I will admit that we can probably give a better error message here, but as per the README, pass-through options must come after pulp options: https://github.com/bodil/pulp#pass-through-options

**Comment by hdgarrood** [comment]
So you should just do `pulp build -O -o lib-gen --censor-warnings`.

**Comment by dszakallas** [comment]
It gives a different error message then: 

```
> pulp build -O -o lib-gen --censor-warnings

* Building project in /Users/david/Projects/collection-benchmarks-purescript
           Src   Lib   All
Warnings   0     0     0
Errors     0     0     0
* Build successful.
* Bundling JavaScript...
Invalid option `--censor-warnings'

Usage: psc-bundle FILE [-o|--output ARG] [-m|--module ARG] [--main ARG]
                  [-n|--namespace ARG] [-r|--require-path ARG]
* ERROR: Subcommand terminated with exit code 1
```

**Comment by natefaubion** [comment]
@szdavid92 That is related to https://github.com/bodil/pulp/issues/174 (You can't pass psa args when using `-O`).

**Comment by hdgarrood** [comment]
As a workaround, I'd recommend running `pulp build` without the `-O` flag, and running `psc-bundle` manually afterwards. I think the command you'll want is just `psc-bundle 'lib-gen/*/*.js' > bundle.js`.

**Comment by dszakallas** [comment]
@hdgarrood Actually I don't want to bundle anything at all. I use [app-module-path](https://www.npmjs.com/package/app-module-path) to make the compiled purescript modules appear on the search path and [I just call my modules](https://github.com/collection-benchmarks/collection-benchmarks-purescript/blob/master/index.js) from native JavaScript. `pulp build -O -o lib-gen` didn't bundle my modules, if i understand correctly.

**Comment by hdgarrood** [comment]
Ah, I see. In that case you don't want the `-O` option at all.

**Comment by dszakallas** [comment]
Ok, thanks for clearing this out for me.
