### ISSUE TITLE
Pulp login should also accept the token as a command line argument

### ISSUE THREAD

**Issue by garyb** [purescript-contrib/pulp#198]
As otherwise it won't be possible to publish from a CI build

**Comment by hdgarrood** [comment]
Ah, ok - are you imagining that you'll run `pulp version` (or just tag) locally, push to github, and then Travis will only run `pulp publish` if the tests pass when it builds that tag?

**Comment by garyb** [comment]
Yeah, exactly - I like the use case I have now, but I'd much rather `pulp publish` when Travis succeeds with tag than having the curl snippet in there. Especially given that this handles gzip now, which I never got around to doing for my travis-scripted-publishing.

The main advantage is it means if someone else submits changes and then I merge & tag & release, I don't then have to clone locally, build, and publish.

Using `pulp login $AUTH_TOKEN` should still be safe too, as Travis will obscure private environment variables in the log.

**Comment by garyb** [comment]
Sorry, I probably should have elaborated a bit more on these issues when I opened them.

**Comment by hdgarrood** [comment]
How do you tag things without cloning locally?

**Comment by garyb** [comment]
Through GitHub, you can make them directly from the Releases tab.

**Comment by hdgarrood** [comment]
Ah, I see. Does `echo $AUTH_TOKEN | pulp login` work?

**Comment by garyb** [comment]
Oh, of course, yes. Or it works in that it attempts to verify the token or something, but #199 happens after that.
