### ISSUE TITLE
Pulp login seems to always fail

### ISSUE THREAD

**Issue by garyb** [purescript-contrib/pulp#199]
It's hard to tell whether it's an issue of the paste not going in perhaps, as there's no visual indication of whether anything happens on paste, so it might be related to that, but currently I get:

```
* ERROR: socket hang up
```

After a few seconds, using a token that has published hundred of libraries previously :wink:

**Comment by garyb** [comment]
I guess if #198 was implemented then at least it would be possible to verify whether there's a problem in the "login" process or whether it is input related.

**Comment by garyb** [comment]
This happens on OSX too it would seem.

**Comment by hdgarrood** [comment]
I tested this on OSX, so I guess that means it isn't just the OS.

What happens if you manually run psc-publish | gzip > pursuit.json.gz and then attempt to upload with something like curl?

**Comment by hdgarrood** [comment]
Oh sorry, this is pulp login. Ok, in that case, what happens if you try to hit api.github.com/user with your token?

**Comment by garyb** [comment]
It succeeds, 200 status and useful looking JSON response.

**Comment by garyb** [comment]
Interestingly, I also tried uploading something using your .sh upload and this happens:

```
Uploading purescript-halogen at 0.6.2. Is this ok? [y/n] y
*   Trying 96.126.102.228...
* Connected to pursuit.purescript.org (96.126.102.228) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate: pursuit.purescript.org
* Server certificate: Let's Encrypt Authority X1
* Server certificate: DST Root CA X3
> POST /packages HTTP/1.1
> Host: pursuit.purescript.org
> User-Agent: curl/7.43.0
> Content-Encoding: gzip
> Accept: application/json
> Authorization: ...SNIP...
> Content-Length: 77469
> Content-Type: application/x-www-form-urlencoded
> Expect: 100-continue
> 
< HTTP/1.1 100 Continue
* We are completely uploaded and fine
< HTTP/1.1 500 Internal Server Error
< Server: nginx/1.4.6 (Ubuntu)
< Date: Thu, 31 Mar 2016 14:47:04 GMT
< Content-Type: text/plain; charset=utf-8
< Content-Length: 0
< Connection: keep-alive
< Set-Cookie: _SESSION=...; Path=/; Expires=Thu, 31-Mar-2016 16:47:03 GMT; HttpOnly
< Vary: Accept, Accept-Language
< 
* Connection #0 to host pursuit.purescript.org left intact
```

**Comment by hdgarrood** [comment]
That "We are completely uploaded and fine" message is weird - I definitely didn't put that in... Also it seems it's a bit premature. Probably not worth worrying about though.

500 errors are usually caused by invalid gzip data in the request body. Can you put the file somewhere so that I can have a look at it?

**Comment by hdgarrood** [comment]
Also are you using the latest version? https://github.com/hdgarrood/dotfiles/blob/f2e337ac3789eb59232413ec39c71bf677c7d55a/bin/upload-pursuit

**Comment by garyb** [comment]
I'll try that in a bit and then open a pursuit issue if I'm still having trouble. Pretty sure I have the latest though, as it's not long since I copied it. 

Any ideas on the login thing, since the GitHub endpoint seems okay?

**Comment by hdgarrood** [comment]
Nope :( if you are able to investigate this any further I'd appreciate it. I can't reproduce this at all.

**Comment by garyb** [comment]
I've tried with a new different token now too, with the same result. I'll do some more digging!

**Comment by garyb** [comment]
What version of Node are you on?

**Comment by hdgarrood** [comment]
5.7.1. Sorry, I just worked out what happened. I was using an older version of `pulp login`; it used to use affjax. I broke it when switching to node-http and accidentally tested the old (working) code instead of the new code.

**Comment by garyb** [comment]
Nevermind, that was the sound of a straw being clutched. It doesn't work for me on 4 or 5.

**Comment by garyb** [comment]
Oh! "Great" :smile:

**Comment by hdgarrood** [comment]
It seems if you write an empty buffer to a HTTP request stream, it doesn't call the callback. Sorry! I hope you weren't digging for ages.

**Comment by garyb** [comment]
No problem! I only just started looking into it again now.

**Comment by garyb** [comment]
Let me know when you cut a new RC and I'll try it out again.

**Comment by hdgarrood** [comment]
Ok, 8.2.0-rc.2 is out.

**Comment by garyb** [comment]
Oh no, haha:

```
* ERROR: Your token was not accepted (403 Forbidden).
```

I get this for both tokens I use, both of which definitely work elsewhere.

**Comment by hdgarrood** [comment]
Argh, I need to include a user-agent header. I should print the body if there is one and if it's an error response.

**Comment by hdgarrood** [comment]
Ok, rc3 is out. :sweat:

**Comment by garyb** [comment]
Huzzah! That works now, thanks.

**Comment by hdgarrood** [comment]
Hooray :) thanks for actually testing this (as it seems I failed to).

**Comment by garyb** [comment]
You're welcome, thanks for implementing this, I'm pretty excited for it :smile:
