### ISSUE TITLE
Broswerify optimization doesn't work

### ISSUE THREAD

**Issue by fluffynukeit** [purescript-contrib/pulp#20]
The browserify command works for me, using either the defaults or the `--to` option.  However, if I include the `-O` or `--optimise` option, I get the following error:

```
* Browserifying project in /home/dan/Code/purescript-puzzler
* Compiling...
psc: Main: openBinaryFile: does not exist (No such file or directory)
* ERROR: Subcommand terminated with error code 1
```

I am using pulp 2.0.0.

**Comment by bodil** [comment]
It seems psc's argument parser has changed a bit since that feature was implemented. `psc --main Main` no longer works, you have to do `psc --main=Main` instead.
