### ISSUE TITLE
Include option to bypass tag-pushing with `pulp publish`

### ISSUE THREAD

**Issue by garyb** [purescript-contrib/pulp#201]
If the tag already exists (pushed by someone else, created via GitHub, etc), then this is unnecessary. 

Also semi-related, it might be worth including an option for where to push to - if I have a local fork cloned, it attempts to push to `origin`, where actually it should be `slamdata` or whatever.

**Comment by hdgarrood** [comment]
Yeah, sounds sensible. I guess we should warn if the remote we're pushing to doesn't match the repository in bower.json as well? We'll have to work out something about canonicalizing repository locators, though, as there are a few different ways of referring to github repositories; https, git, ssh... that shouldn't be too difficult though.

**Comment by hdgarrood** [comment]
I don't think we need an option to bypass tag pushing, I think we can just check the remote and not push tags if they already exist on the remote.

**Comment by garyb** [comment]
That works too, I just figured that it might be trickier to figure out which remote to push to when there are multiple options.

**Comment by hdgarrood** [comment]
Oh, no - I'm proposing that we add an option for which remote to push to (and use 'origin' as the default) but warn and confirm if this appears to not match the repository in bower.json.

**Comment by hdgarrood** [comment]
Oh maybe we should use the bower registry as well / instead? Hmm.

**Comment by garyb** [comment]
Oh sorry, I see. Sounds good :+1: 

I think the `bower.json` is a better source, the bower registry has lots of "incorrect" registrations as we've moved things around, promoted to contrib/core, etc. that still work because of redirects, but don't reflect the current order of things.

**Comment by hdgarrood** [comment]
But the bower registry is what gets used when you actually try to `bower install foo`, so maybe we should attempt to follow those redirects? Agh, this would be much easier if we had a normal registry.

**Comment by garyb** [comment]
I've thought of another potential problem with not having the option to disable pushing: I doubt Travis has write access to the repo. I guess that's also solved if we do the tag existence check first though.

**Comment by hdgarrood** [comment]
Because of things like `.netrc`, `.ssh/config`, and various git url formats (HTTPS, SSH, etc), trying to be clever about trying to work out whether tags need to be pushed anywhere is now seeming to not be worth the effort, so I think I'm just going to add a `--push-to REMOTE` option and a `--no-push` flag.
