### ISSUE TITLE
pulp server throws Error: spawn psc ENOENT

### ISSUE THREAD

**Issue by doivosevic** [purescript-contrib/pulp#202]
I have done a clean install of pulp with `npm i -g pulp browserify bower` and have done `pulp init` + `pulp server` like said and it throws.

```
Dito@DESKTOP-74I7GP7 C:\Users\Dito\Desktop\git\Fusky\front-ps                                  
> pulp init                                                                                    
* Generating project skeleton in C:\Users\Dito\Desktop\git\Fusky\front-ps                      
bower cached        git://github.com/purescript/purescript-console.git#0.1.1                   
bower validate      0.1.1 against git://github.com/purescript/purescript-console.git#^0.1.0    
bower cached        git://github.com/purescript/purescript-eff.git#0.1.2                       
bower validate      0.1.2 against git://github.com/purescript/purescript-eff.git#^0.1.0        
bower cached        git://github.com/purescript/purescript-prelude.git#0.1.5                   
bower validate      0.1.5 against git://github.com/purescript/purescript-prelude.git#^0.1.0    
bower install       purescript-console#0.1.1                                                   
bower install       purescript-eff#0.1.2                                                       
bower install       purescript-prelude#0.1.5                                                   

purescript-console#0.1.1 bower_components\purescript-console                                   
└── purescript-eff#0.1.2                                                                       

purescript-eff#0.1.2 bower_components\purescript-eff                                           
└── purescript-prelude#0.1.5                                                                   

purescript-prelude#0.1.5 bower_components\purescript-prelude                                   

Dito@DESKTOP-74I7GP7 C:\Users\Dito\Desktop\git\Fusky\front-ps                                  
> pulp server                                                                                  
* Server listening on http://localhost:1337/                                                   
events.js:154                                                                                  
      throw er; // Unhandled 'error' event                                                     
      ^                                                                                        

Error: spawn psc ENOENT                                                                        
    at exports._errnoException (util.js:890:11)                                                
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)                  
    at onErrorNT (internal/child_process.js:348:16)                                            
    at _combinedTickCallback (node.js:383:13)                                                  
    at process._tickCallback (node.js:407:11)                                                  
```

**Comment by hdgarrood** [comment]
Yeah, this is a known bug which I would like to fix by doing #151. In the meantime, you can work around it by doing either of the following:
1. Use webpack directly, with [purescript-webpack-plugin](https://www.npmjs.com/package/purescript-webpack-plugin). (I recommend this one)
2. Install the PureScript compiler binaries in some other way; for example, by downloading a binary bundle from the releases tab on the compiler GitHub repo. This problem is caused by the command on your PATH being `psc.cmd` rather than `psc.exe` (as far as I know, only the npm distribution uses a wrapper script like this).

**Comment by hdgarrood** [comment]
@bodil maybe we should remove the `pulp server` part from the readme until this is fixed? Currently this will happen to everyone who follows the instructions on Windows.

**Comment by bodil** [comment]
Add a note about problems on Windows instead, maybe?

**Comment by DominikDitoIvosevic** [comment]
živio I I

**Comment by DominikDitoIvosevic** [comment]
on iiiiiiiiiii

**Comment by doivosevic** [comment]
I apologize. My phone starts clicking randomly sometimes :D

**Comment by stefanholzmueller** [comment]
I upgraded pulp to 8.2.0 today and got a very similar error for `pulp test` after a `pulp init` (on Windows).

@hdgarrood I'd like to try your recommended workaround, can you please give more detailed instructions? I fail to see a connection between purescript-webpack-plugin and pulp.

**Comment by hdgarrood** [comment]
`pulp server` is a thin wrapper around webpack right now, using a rather old version of the purescript webpack integration stuff. If you want a dev server it is often a good idea to use that integration stuff directly, as it's more configurable, and easier to keep up to date. I'm not too familiar with it but there are instructions in the README: https://www.npmjs.com/package/purescript-webpack-plugin

**Comment by hdgarrood** [comment]
Wait, if you got this for pulp test it's a different issue. Could you please open a new issue with more details?

**Comment by hdgarrood** [comment]
Not sure why I reopened this, as it's subsumed by #151.
