### ISSUE TITLE
Pulp build --optimise fails on Windows

### ISSUE THREAD

**Issue by ulyssesdotcodes** [purescript-contrib/pulp#203]
Just started looking into pulp/purescript. These are the steps I have performed so far:

`npm install -g purescript pulp bower`

Running `pulp init` and `pulp run` and `pulp build` work as expected. `pulp build --optimise` (originally found this error using `--to`) cause this error:

```
* Building project in c:\Users\Ulysses\Development\psc-test
psc: No files found using pattern: src/**/*.js
* Build successful.
* Bundling JavaScript...
Error in module Prelude (Foreign):

  The module could not be parsed:
  lexical error @ line 217 and column 14

* ERROR: Subcommand terminated with exit code 1
```

Any help is appreciated!

**Comment by hdgarrood** [comment]
This is a bug in the latest version of `psc-bundle` (0.8.3); see purescript/purescript#1966. For now, I'd recommend specifying version 0.8.2 of `purescript` in your package.json, like this:

```
{
  ...
  "dependencies": {
    "purescript": "0.8.2"
  }
}
```

**Comment by ulyssesdotcodes** [comment]
Cheers @hdgarrood!
