### ISSUE TITLE
Split vendor and app-specific code into separate bundles

### ISSUE THREAD

**Issue by menelaos** [purescript-contrib/pulp#204]
It would be cool if `pulp browserify` could split the resulting JS into separate bundles discriminating on whether it is (rapidly changing) application code or (slowly changing) library code.

This would be similar to what one can do with `browserify --no-bundle-external ...` and `browserify -r ...`

That way, the build time for the `browserify` step could be reduced and users might get faster load times when caching part of the code.

**Comment by hdgarrood** [comment]
This does sound interesting. Do you know how easy it is to accomplish using `browserify` directly?

**Comment by ttbodil** [comment]
I'd call this outside of Pulp's scope, but I do want to figure out a way of just being able to pass arguments to Browserify... Perhaps we should just go through all the Browserify API's options and add corresponding command line arguments for them where appropriate.

**Comment by menelaos** [comment]
@hdgarrood
No, unfortunately I don't know. I'm not sure if it can be done using only `browserify`.
For splitting my own code and third-party JS libraries like `react` into two separate files `vendor.js` and `app.js`, I'd do something like this:

```
psc -f "src/**/*.js" -f "bower_components/purescript-*/src/**/*.js" "src/**/*.purs" "bower_components/purescript-*/src/**/*.purs"
```

```
psc-bundle "output/*/*.js" --output app.js --module Main --main Main
```

```
browserify -r react -r react-dom > vendor.js
```

For purescript modules it is more complicated if one wants to keep dead code elimination. 

Now that I've thought more about this issue, it is probably not worth implementing.
