### ISSUE TITLE
Passing  through to browserify

### ISSUE THREAD

**Issue by doivosevic** [purescript-contrib/pulp#205]
Could we get an option to pass commands through to browserify?
Maybe if pulp does not have the option first try it against browserify and then psc?

**Comment by hdgarrood** [comment]
Could you please explain a little more about your situation? What are you trying to do at a high level, what commands did you run, and so on? It's difficult to work out what the right approach is without this context.

**Comment by doivosevic** [comment]
I thought there was an issue with browserify not being able to find my angular files.
I ran:

```
> pulp browserify --to "dist/bundle.js" --main "Index"
* Browserifying project in \git\Fusky\front-ps
* Building project in \git\Fusky\front-ps
           Src   Lib   All
Warnings   0     0     0
Errors     0     0     0
* Build successful.
* Browserifying...
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module 'angular2/browser' from '\git\Fusky\front-ps\output\Angular.Browser'
```

But I seem to have fixed it since. Not sure how exactly :/
Anyhow I apologise for my low quality question since my problem seems to be unrelated

**Comment by hdgarrood** [comment]
No need to apologise. :)

That kind of looks to me like you needed to `npm install` angular first, perhaps? Anyway probably not worth worrying too much about.
