### ISSUE TITLE
pulp test Error: spawn psc ENOENT

### ISSUE THREAD

**Issue by stefanholzmueller** [purescript-contrib/pulp#209]
`pulp test` fails every time with the following error:

```
* Building project in c:\Users\bear\tmp\pulptest
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn psc ENOENT
    at exports._errnoException (util.js:855:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:455:9)
    at process._tickCallback (node.js:369:17)
    at Function.Module.runMain (module.js:432:11)
    at startup (node.js:141:18)
    at node.js:980:3
 * ERROR: Subcommand terminated with exit code 1
```

Got this in a real project, but also after a fresh `pulp init` in an empty directory. `pulp --version` output:

```
Pulp version 8.2.1
psc version 0.8.5.0 using c:\Users\bear\AppData\Roaming\npm\psc
c:\Users\bear\AppData\Roaming\npm\psc.cmd
```

May be somehow related to #202 because the error is nearly the same. It seems to be a Windows problem, too.

I'm kind of lost right now, any ideas how to debug this?

**Comment by hdgarrood** [comment]
This is weird. Are you running this inside an npm script? Does `pulp build` work?

**Comment by stefanholzmueller** [comment]
No, I just enter `pulp test` in the command line (either the standard "cmd" or "Git Bash").
`pulp build` throws the very same error.

I tried `npm i -g pulp browserify bower` but this did not help.
However, I installed pulp on another machine from scratch and there it works. :(

BTW, I upgraded from pulp 6.2.0 recently - this is when the problem manifested.

**Comment by hdgarrood** [comment]
What are the contents of `c:\Users\bear\AppData\Roaming\npm`?

**Comment by stefanholzmueller** [comment]
```
11.05.2016  15:08    <DIR>          .
11.05.2016  15:08    <DIR>          ..
11.05.2016  15:08               290 bower
11.05.2016  15:08               198 bower.cmd
11.05.2016  15:08               302 browserify
11.05.2016  15:08               210 browserify.cmd
31.12.2015  20:13    <DIR>          etc
11.05.2016  15:08    <DIR>          node_modules
20.02.2016  21:50               306 psa
20.02.2016  21:50               214 psa.cmd
09.05.2016  14:22               302 psc
09.05.2016  14:22               316 psc-bundle
09.05.2016  14:22               224 psc-bundle.cmd
09.05.2016  14:22               312 psc-docs
09.05.2016  14:22               220 psc-docs.cmd
09.05.2016  14:22               324 psc-ide-client
09.05.2016  14:22               232 psc-ide-client.cmd
09.05.2016  14:22               324 psc-ide-server
09.05.2016  14:22               232 psc-ide-server.cmd
09.05.2016  14:22               318 psc-publish
09.05.2016  14:22               226 psc-publish.cmd
09.05.2016  14:22               210 psc.cmd
09.05.2016  14:22               304 psci
09.05.2016  14:22               212 psci.cmd
11.05.2016  15:08               286 pulp
11.05.2016  15:08               194 pulp.cmd
              22 Datei(en),          5.756 Bytes
```

**Comment by hdgarrood** [comment]
Cool ok, and what is the `psc` file in there? Is it a plain text file? Can you try renaming it temporarily, say, to `psc.bak`, and see if that makes any difference?

**Comment by stefanholzmueller** [comment]
Doesn't seem to make a difference, except `pulp --version` now prints:

```
Pulp version 8.2.1
psc version 0.8.5.0 using c:\Users\bear\AppData\Roaming\npm\psc.cmd
```

**Comment by stefanholzmueller** [comment]
Contents of `psc`:

```
#!/bin/sh
basedir=`dirname "$0"`

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/node_modules/purescript/bin/psc.js" "$@"
  ret=$?
else 
  node  "$basedir/node_modules/purescript/bin/psc.js" "$@"
  ret=$?
fi
exit $ret
```

**Comment by hdgarrood** [comment]
Uh, I'm not sure what's going on here. What version of npm do you have?

**Comment by stefanholzmueller** [comment]
npm 3.3.12, node 5.3.0
I'll probably just reinstall node/npm next. gtg soon, will report tomorrow or so.

**Comment by stefanholzmueller** [comment]
Problem disappeared after reinstalling node (and deleting AppData\Roaming\npm and AppData\Roaming\npm-cache, just to be sure). Whatever! :)
Thanks for your help though @hdgarrood

**Comment by stefanholzmueller** [comment]
Note to self, or if anyone else has this problem:
I ran into the error again (with Atom/ide-purescript) and apparently fixed it by just deleting the directory AppData\Roaming\npm-cache
