### ISSUE TITLE
0.9 compatibility

### ISSUE THREAD

**Issue by hdgarrood** [purescript-contrib/pulp#211]
- [x] The `--ffi` flag is being removed from `psc`. Pulp should no longer need to worry about FFI files at all now, since `psc` will locate them based on the purs file name.
- [x] The `.psci` file is being removed, and replaced with globs passed on the command line.

**Comment by ttbodil** [comment]
Do we want to stay backwards compatible? Sounds like that'd be a bit of an effort.

**Comment by hdgarrood** [comment]
Yeah, I'm not sure it would be worth the effort. The rest of the ecosystem doesn't seem to have started worrying too much about backwards compatibility yet either. It's not hard to install an older version of pulp either locally or globally if you're staying on 0.8, I think.

I vote we reuse the current mechanism in `Pulp.Validate` which just throws an error saying your `psc` is too old, please either upgrade psc to version X or downgrade pulp to version Y.

**Comment by hdgarrood** [comment]
Oh, also:
- [x] `pulp init` should create a bower.json that depends on `purescript-psci-support` so that psci works.

**Comment by hdgarrood** [comment]
I think this is everything for now. Once an RC for 0.9 is out, I'll merge this and test a bit more thoroughly.
