### ISSUE TITLE
Binary Releases of pulp?

### ISSUE THREAD

**Issue by clinuxrulz** [purescript-contrib/pulp#213]
Any chance of binary releases of pulp?

Sometimes `npm` is really slow for me.

8:40am: `sudo npm install pulp -g`

Its now 5pm and only 30% progress.

**Comment by hdgarrood** [comment]
Wow, that's awful! Usually for me it only takes a minute or so. What version of npm are you using?

**Comment by clinuxrulz** [comment]
```
Clintons-Mac-mini:~ clintonselke$ npm --version
3.9.0
```

**Comment by hdgarrood** [comment]
Ah ok. Perhaps have a look on the npm cli issue tracker then? I'd rather not try to do 'binary' releases if we can get away with it, because it would make releasing new versions of pulp quite a bit more complicated than it is now.

**Comment by clinuxrulz** [comment]
Actually I think it might me my internet connection today. I seem to have really high latency.

**Comment by clinuxrulz** [comment]
Good news! Pulp finished installing now. I upgraded node as well and not just npm and all went well.

```
Clintons-Mac-mini:~ clintonselke$ sudo npm cache clean -f
Password:
npm WARN using --force I sure hope you know what you are doing.
Clintons-Mac-mini:~ clintonselke$ sudo npm install -g n
/usr/local/bin/n -> /usr/local/lib/node_modules/n/bin/n
/usr/local/lib
└── n@2.1.0 

Clintons-Mac-mini:~ clintonselke$ sudo n stable
```
