### ISSUE TITLE
More visible separation between compiles? (optional empty/filled lines between)

### ISSUE THREAD

**Issue by doivosevic** [purescript-contrib/pulp#214]
Would it be possible  to have an optional flag which appends empty lines between two lines because when alttabbing between windows every time I get distracted by empty lines inside an error and have to spend extra time finding where the previos output ends and the new begins.
I hope this doesn't sound to silly.

http://i.imgur.com/IWtH1dQ.png

**Comment by hdgarrood** [comment]
Yeah, sounds sensible. Is there a reason to add a flag? - is there any reason not to add a visual separation all the time?

**Comment by doivosevic** [comment]
Yeah, my friend just asked me that after I asked him for an opinion. As far as I'm concerned I'm ok with it but maybe some people would like for it to stay like it was or to maybe add more/less newlines than you might.
It really depends on how complicated it might be for you or if you'd like to minimize the number of flags (but who doesn't like customization, eh?)

**Comment by LiamGoodacre** [comment]
:+1: for visual separation without a flag.
