### ISSUE TITLE
--to nonExistentFolder/index.js throws error

### ISSUE THREAD

**Issue by texastoland** [purescript-contrib/pulp#217]
I expected the folder to be created. If it's by design perhaps an explanatory message could be printed?

**Comment by hdgarrood** [comment]
Agree that this should just create the folder.

**Comment by texastoland** [comment]
Started to take a look and found a [SO answer](http://stackoverflow.com/questions/12906694/fs-createwritestream-does-not-immediately-create-file). Apology if it's rudimentary.

**Comment by hdgarrood** [comment]
That's good information; we probably should be waiting for the 'open' event. I don't think that's related to this bug, though.

**Comment by texastoland** [comment]
I interpreted it to mean `open` is when to ensure the directory exists.

**Comment by hdgarrood** [comment]
I think we need to ensure the directory exists before we call `createWriteStream`.
