### ISSUE TITLE
minimatch is out of date

### ISSUE THREAD

**Issue by hdgarrood** [purescript-contrib/pulp#218]
> npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

I'd guess it's very unlikely that we need to worry about this DoS issue, but people installing pulp might not always be able to work that out.

**Comment by sotojuan** [comment]
This can be closed now right?

**Comment by hdgarrood** [comment]
Yes, thanks.
