### ISSUE TITLE
pulp server doesn't show "Hello sailor!"

### ISSUE THREAD

**Issue by arafangion** [purescript-contrib/pulp#219]
I am extremely new to purescript and pulp, I had wished to serve a website using it.

I am expecting to see "Hello sailor!" on the command line when I run the server, then I hope to investigate how to use this for a dynamic web site.

However, the following occurs, please note the invalid option, the errors, and the lack of 'Hey Sailor'.

After performing `npm install -g purescript pulp bower`, followed by a `pulp init`,  the following occurs when I run `pulp server`:

`% pulp server
- Server listening on http://localhost:1337/
- Invalid option `--require-path=../'

Usage: psc [FILE] [-o|--output ARG] [--no-tco] [--no-magic-do] [--no-opts]
           [-v|--verbose-errors] [-c|--comments] [--source-maps]
           [-p|--no-prefix] [--json-errors]

Hash: 3ef54b8f9609f9e9c044
Version: webpack 1.13.1
Time: 557ms
     Asset     Size  Chunks             Chunk Names
    app.js  1.77 kB       0  [emitted]  main
app.js.map  1.61 kB       0  [emitted]  main
chunk    {0} app.js, app.js.map (main) 31 bytes [rendered]
    [0] ./src/.webpack.js 31 bytes {0} [built] [1 error]

ERROR in ./src/Main.purs
Module build failed: Error: Process terminated with code 1
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/pulp/node_modules/purs-loader/index.js:5081:32)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
 @ ./src/.webpack.js 1:0-22
webpack: bundle is now VALID.
webpack: bundle is now INVALID.
- Invalid option `--require-path=../'

Usage: psc [FILE] [-o|--output ARG] [--no-tco] [--no-magic-do] [--no-opts]
           [-v|--verbose-errors] [-c|--comments] [--source-maps]
           [-p|--no-prefix] [--json-errors]

Hash: 3ef54b8f9609f9e9c044
Version: webpack 1.13.1
Time: 210ms
chunk    {0} app.js, app.js.map (main) 31 bytes
     + 1 hidden modules

ERROR in ./src/Main.purs
Module build failed: Error: Process terminated with code 1
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/pulp/node_modules/purs-loader/index.js:5081:32)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
 @ ./src/.webpack.js 1:0-22
webpack: bundle is now VALID.
^C
%`

As a comparison, the following is what happens when I run `pulp run`:

`% pulp run 
- Building project in/Users/arahael/dev/tmp
- Build successful.
  Hello sailor!`

Thanks.

**Comment by arafangion** [comment]
The versions of everything are as follows:

npm: 3.3.12
pulp: 9.0.1
psc: 0.9.1
bower: 1.7.9

Running Mac OS X 10.11.5 (OS X El Capitan)

**Comment by hdgarrood** [comment]
Unfortunately `pulp server` doesn't work with version 0.9 of the compiler yet. In the meantime I suggest you either use `pulp build --to main.js` in conjunction with a package like npm's `serve`, or use webpack with purs-loader.

**Comment by arafangion** [comment]
Thanks @hdgarrood, "suppi" from IRC helped me out here, suggesting `python -m SimpleHTTPServer&
pulp --watch browserify --to app.js`.

However it turns out I was hoping that the server would be dynamic (i.e., to support server-side queries), so I'l need to look elsewhere, and I also got a few suggestions for those.

**Comment by hdgarrood** [comment]
This is subsumed by #151.
