### ISSUE TITLE
Error when trying to publish: `ERROR: The header content contains invalid characters`

### ISSUE THREAD

**Issue by garyb** [purescript-contrib/pulp#222]
Originally was purescript/pursuit#229. It looks like this:

```
Publishing purescript-these at v1.0.0. Is this ok? [y/n] y
* Uploading documentation to Pursuit...
* ERROR: The header content contains invalid characters
```

So far I've seen it with just two libraries out of many more that worked succesfully:
- purescript-zclipboard
- purescript-these

**Comment by hdgarrood** [comment]
Have you seen this at all recently? Also do you remember what OS and node version you were using?

**Comment by garyb** [comment]
It occurred on MacOS and Windows 10, but I couldn't tell you exactly what node version it was - it probably differed by OS, but pretty sure both would have been in the 6.x range.

Both libraries seem to be on Pursuit now, so I guess it isn't occurring anymore though!

**Comment by hdgarrood** [comment]
I'm going to close this in the hope that it was a bug in node's http client library that has now been fixed. If anyone sees this again, please feel free to reopen.
