### ISSUE TITLE
pulp doesn't detect when psc exits due to being killed

### ISSUE THREAD

**Issue by kika** [purescript-contrib/pulp#224]
See https://github.com/purescript/purescript/issues/2259 item number 7
psc is being killed by the system, but pulp happily reports `Build successful`

**Comment by hdgarrood** [comment]
I'm trying to reproduce this on Ubuntu with node v6.9.2 but it's working as expected for me; if I start `pulp build` in one window and then run `pkill psc` or `pkill -9 psc`, in both cases, I get "SIGTERM" or "SIGKILL" printed respectively, followed by "Process terminated with exit code 1".

I wonder if this might be a bug in node.js.

**Comment by hdgarrood** [comment]
Assuming this is a node.js bug which has since been fixed. Please reopen if you see this again.
