### ISSUE TITLE
pulp browserify -O runtime error

### ISSUE THREAD

**Issue by codygman** [purescript-contrib/pulp#227]
Code is erased that breaks the program, minimum repro here:

https://github.com/codygman/purescript-optimize-issue

**Comment by codygman** [comment]
Hm, as I dig deeper it seems like this might be a problem with psc-bundle.

**Comment by codygman** [comment]
In my search I've ended up at:

https://github.com/bodil/pulp/blob/0c3b2b9918cbd1cfd815424d51411ccba984fa39/src/Pulp/Browserify.js#L12

I have figured out that browserifyBundle$prime reproduces the issue whereas browserifyIncBundle$prime does not.

**Comment by codygman** [comment]
As I read more about browserify, I'm guessing purescript and/or pulp has it's own browserify transforms. Where can those be found?

**Comment by hdgarrood** [comment]
Hi, thanks for looking into this. I'll take a closer look when I have time. For now:

> As I read more about browserify, I'm guessing purescript and/or pulp has it's own browserify transforms. Where can those be found?

I'm fairly certain that this is not the case - what gave the impression that it was?

**Comment by hdgarrood** [comment]
Hm, where is `dataKeys` defined?

**Comment by kritzcreek** [comment]
@hdgarrood I think I found it here: https://github.com/ptol/purescript-sigment/blob/2b75024f6d3f922cb351881ac7272c3785fe89d5/src/Dom.js#L22

**Comment by codygman** [comment]
Cool, now how would one go about figuring out how it got optimized away?

**Comment by natefaubion** [comment]
I'd make a small test module that defines a few things in the same way as that FFI file and see what psc-bundle does with it. psc-bundle is supposed to leave declarations it doesn't understand alone, but it could be pruning that for some reason?

**Comment by hdgarrood** [comment]
This is indeed a psc-bundle issue (see my most recent comment in https://github.com/purescript/purescript/issues/2290, that is https://github.com/purescript/purescript/issues/2290#issuecomment-260737638) and therefore I'm going to close it.
