### ISSUE TITLE
Include questions for pulp init to integrate better with pursuit

### ISSUE THREAD

**Issue by Risto-Stevcev** [purescript-contrib/pulp#228]
Pursuit requires a few things to be included in `bower.json` in order to be able to publish something. For example, the `bower.json` needs a `license` field and I think a `repository` field.

What do you think of adding a couple of questions as part of `pulp init`, much like `npm init` and `bower init`, to include at least the bare minimum fields necessary to publish to pursuit?

**Comment by hdgarrood** [comment]
I think we might have discussed this earlier on this issue tracker, would you mind having a quick look?

**Comment by Risto-Stevcev** [comment]
Ah, sorry it's a duplicate of #78
