### ISSUE TITLE
Speed up the tests

### ISSUE THREAD

**Issue by hdgarrood** [purescript-contrib/pulp#233]
They take about 3 minutes on my machine which is ridiculous. I think it might be node.js' fault.

**Comment by bodil** [comment]
They used to take 10 minutes on mine. Given that they're integration tests, I'm not sure that's unreasonable, but if you have ideas for speeding them up, obvs go for it.

**Comment by hdgarrood** [comment]
None right now, sadly, but I want to look into it more eventually.

**Comment by bodil** [comment]
Come to think of it, I suspect most of the time is spent running `pulp init`, if we cache that we could probably decrease test time by as much as an order of magnitude.

**Comment by hdgarrood** [comment]
I tried that in the `faster-tests` branch and it didn't seem to have much effect, sadly.
