### ISSUE TITLE
Browserify should not write the file in between

### ISSUE THREAD

**Issue by eproxus** [purescript-contrib/pulp#237]
I'm trying to make a poor man's integration of PureScript together with Brunch, where I manually compile the PureScript code into a vendor folder, and then have Brunch watch that folder.

The problem is that `pulp browserify` and `pulp -w browserify` first write the JS file, then run Browserify on it which empties the file, and then writes it back again. Watching this with Brunch messes up the compilation with error messages such as:

```
02 Dec 10:35:00 - error: Compiling of web/static/vendor/purescript.js failed. File web/static/vendor/purescript.js data is invalid.
```

Because Brunch sees the file has change, and tries to read it while it's being modified by Browserify.

The Browserify step in Pulp should run in memory and then only write the file once the end result has been produced. This would make Pulp more compatible with watching tools.

**Comment by hdgarrood** [comment]
What is the exact command you're running?

**Comment by eproxus** [comment]
```
$ pulp browserify --optimise --to dist/app.js
```

(optionally add `--watch`, which exhibits the same behaviour)

Managed to solve it with `--then "cp dist/app.js web/static/vendor/purescript.js"` but it would be nice to see the improvement in Pulp nonetheless (to minimize confusion).

**Comment by hdgarrood** [comment]
Are you certain that's what is happening? Here's the relevant source: https://github.com/bodil/pulp/blob/c93cc7d83d70a7b7c50cab829fda19c1e468240c/src/Pulp/Browserify.purs#L79-L86

It looks to me like Pulp opens the file, calls Browserify, pipes Browserify's result into the file, and finally closes the file. So the file is only opened and closed once by Pulp, if the code is doing what it ought to be doing.

**Comment by eproxus** [comment]
Two observations made me draw that conclusion:

* Brunch watching that JS-file triggered twice with the error described above
* Looking at the file in Sublime Text showed it being written, then empty, then with content again

Could it be that the file is just very large and takes some time to write, and a fast watcher will ready the content before it is completely written? Doing the `--then "cp ..."` might be atomic from the file system... (which would be why it works better)

**Comment by hdgarrood** [comment]
At the moment, Pulp opens the output file before it calls browserify, so yes, the file will certainly be open for a very long time (in computer terms), as browserify will have to read and parse a bunch of other files to do what it needs to do.

I suppose we could address this by just moving your workaround into pulp itself - use a temporary file, and then when it's done, move it to the destination path. I guess that's probably good to do anyway, since it means that if an error occurs halfway through for whatever reason, the output file you specified won't exist (as opposed to it being there but empty or half full of garbage).

**Comment by eproxus** [comment]
Sounds good! In the end, I got it to work with `--then` but this would of course be a nice property of Pulp itself 😄

**Comment by eproxus** [comment]
Many thanks! 🙇
