### ISSUE TITLE
psc-package support

### ISSUE THREAD

**Issue by hdgarrood** [purescript-contrib/pulp#243]
I am fairly sure that this is an exhaustive list of the ways Pulp depends on Bower:

* We check for the existence of `bower.json` to ascertain whether we're inside a purescript project
* We read the project's name from the bower file for prompting during `pulp publish`
* We use `bower_components` paths in globs
* We create a `bower.json` file during `pulp init`.

To support psc-package, we would need to change all of these things. I think for a while, we should support both, depending on the existence of `psc-package.json` and `bower.json`: if both exist, we would want to treat it as a psc-package project, if only bower.json exists, it's a bower project.

Presumably `psc-package.json` contains the package name, so that's fine for `pulp publish`. Changing the glob paths is very easy too, and creating a default `psc-package.json` should also be pretty easy, although I'm not sure if we're quite ready for this to be the default yet. It might make sense to release a version of Pulp which does everything listed here but which doesn't change `pulp init` so that psc-package is an explicit opt-in.

**Comment by thoradam** [comment]
I think I have everything except `pulp publish`, what should that do for psc-package projects? Just tag in git, docs in pursuit and then print a message a about maybe creating a PR in [purescript/package-sets](https://github.com/purescript/package-sets)?

**Comment by hdgarrood** [comment]
On second thoughts, I think we should leave publishing as is for now, as package authors should continue to publish to bower for the time being imo.

**Comment by thoradam** [comment]
Ok cool ^_^
