### ISSUE TITLE
Add the option of using purescript version in `npm bin`

### ISSUE THREAD

**Issue by themoritz** [purescript-contrib/pulp#246]
I have multiple PureScript projects that require different versions of the compiler, so I install them locally (under `./node_modules/purescript`, relative to my project) by adding an entry to the dependencies in `package.json`.

It would be great to have the option of having pulp use that version of the compiler (i.e., by invoking `` `npm bin`/psc ``). IMHO, even have it the default to look there first, and then on `$PATH`.

**Comment by LiamGoodacre** [comment]
If you invoke pulp via an npm script defined in your `package.json`, for example:
```javascript
{
  ...
  "scripts": {
    "build": "pulp build"
  }
  ...
}
```

You can then run `npm run build` and I think it will pick up the local `psc`.

**Comment by themoritz** [comment]
That's a good idea! I'm now using

```json
  "scripts": {
    "pulp": "pulp"
  }
```

and then `npm run pulp -- build` to simulate what I need.
