### ISSUE TITLE
pulp browserify: ERROR: EXDEV: cross-device link not permitted, rename '/tmp/pulp-output...' -> 'app.js'

### ISSUE THREAD

**Issue by koterpillar** [purescript-contrib/pulp#252]
On a fresh Pulp project, `pulp browserify --to app.js` fails with:

```
* ERROR: EXDEV: cross-device link not permitted, rename '/tmp/pulp-output117117-32174-1bw52e5.ljrmrevcxr' -> 'app.js'
```

Steps to reproduce:

```
mkdir pulptest
cd pulptest
pulp init
pulp browserify --to app.js
```

The output (build omitted) is:

```
* Browserifying project in /somewhere/pulptest
* Building project in /somewhere/pulptest
* Build successful.
* Browserifying...
* ERROR: EXDEV: cross-device link not permitted, rename '/tmp/pulp-output117117-32407-smcg5c.5uerk9' -> 'app.js'
```

Note that I have `/tmp` mounted as `tmpfs`:

```
$ mount | grep ' /tmp '
tmpfs on /tmp type tmpfs (rw,nosuid,nodev)
```

It seems that the offending call is [FS.rename](https://github.com/bodil/pulp/blob/master/src/Pulp/Build.purs#L131). It is ultimately a wrapper to `rename(2)`, which doesn't allow renaming across filesystems.

**Comment by hdgarrood** [comment]
Maybe let's switch it to use the corresponding function from fs-extra which takes care of moving files across file systems.

**Comment by commandodev** [comment]
I'm also experienceing this where /tmp is in a different partition from where I want app.js. Is there a similar setting to npm where you can set tmp's location in pulp?

**Comment by hdgarrood** [comment]
There isn't in pulp as far as I recall but the underlying library might allow setting it via an environment variable.

**Comment by garyb** [comment]
I tried updating to 10.0.1 today and I'm also seeing this error now. It didn't happen with 10.0.0, if that is useful information at all?

**Comment by hdgarrood** [comment]
Yeah, that's what I'd expect as we only started using a temporary file recently, in order to fix some other bug (can't remember off the top of my head, see the changelog).

**Comment by garyb** [comment]
Oh right, there is a changelog :smile: I was looking at the github releases, but there's nothing there.

**Comment by michallepicki** [comment]
The same error when trying to do `pulp build -O --to output.js`
