### ISSUE TITLE
pulp does not work with Development Builds of purs

### ISSUE THREAD

**Issue by sloosch** [purescript-contrib/pulp#253]
Using a development build of purescript the version information given by `psc --version` will change to e.g. `0.10.6 [development build; commit: c48f74139e94b43c7ecec726d4b280303ae995e0]` since this is not a  Semantic Version the used `purescript-versions` module fails to parse the version and pulp will show the error `Unable to parse the version from psc. (It was: 0.10.6 [development build; commit: c48f74139e94b43c7ecec726d4b280303ae995e0])`

Current work-a-round for me was to change the compiled "purs.js" file by searching for `Data_Version_Haskell.parseVersion(v)` and change it to hard-coded `Data_Version_Haskell.parseVersion("0.10.17")`

Are there plans to support Development Builds?

**Comment by hdgarrood** [comment]
Ah, I hadn't realised that this would cause a problem. I think we could fix this by ignoring any text in the output of `psc --version` after the first space character. I'd accept a PR to do that.
