### ISSUE TITLE
`pulp run`'s loader stub file can interfere with module names, should be kept in a temp directory

### ISSUE THREAD

**Issue by felixSchl** [purescript-contrib/pulp#26]
The README does not make specific mention of it but am I correct to assume that a `pulp init && pulp run` should work without errors?

I am getting:

```
...
on (exports, require, module, __filename, __dirname) { require('Main').main();
                                                                       ^
TypeError: Object #<Object> has no method 'main'
...
```

**Comment by felixSchl** [comment]
`pulp init && pulp test` works, btw. I think it has to do with the node env not being set correctly.

**Comment by felixSchl** [comment]
It's because main.js is picked up as the main module, but the default skeleton creates a `Main` purescript module, which results in `output/Main/index.js`. Node will import `main.js` on `require('Main')`, rather than `Main/index.js`.

**Comment by bodil** [comment]
Proposed solution would be to not store the wrapper file inside the build directory at all, rather using the `temp` module to store it somewhere out of the way, then get rid of it automatically when it's no longer needed.

**Comment by felixSchl** [comment]
I appreciate it's not an all encompassing solution but that is besides the point of the pull request. The initial experience of starting with pulp is what mattered to me. If I change things, I can expect unforeseen things to happen.

**Comment by bodil** [comment]
I appreciate that, I'd still like to get the correct solution in asap. And I'm working on it as we speak, give me a moment. :)

**Comment by felixSchl** [comment]
That commit introduces a Type error in `run.js` on line 22. Just add the additional parameter to `fs.write` and it works: felixSchl/pulp@908600e56908e42848713781d6f13e423794e8ed

**Comment by bodil** [comment]
That's curious. What Node version are you on, just for reference? The docs have that parameter down as optional.

**Comment by felixSchl** [comment]
[The docs](https://nodejs.org/api/fs.html#fs_fs_write_fd_data_position_encoding_callback) specify the parameter as optional only if the other optional parameter `position` has been specified - note the nested brackets. You can [refer to the implementation](https://github.com/joyent/node/blame/master/lib/fs.js#L597) which has not changed since mid july 2013.

**Comment by bodil** [comment]
The code seems to willingly accept both, but I agree with your interpretation of the doc. JS is terrible. :(

It did run correctly in its previous form on my v0.12.0 version of Node, though, which is why I'm puzzled.
