### ISSUE TITLE
Add a `--silent` option

### ISSUE THREAD

**Issue by jgoux** [purescript-contrib/pulp#261]
Hello,

would it be possible to add a `--silent` option to `pulp build` and `pulp run` commands so we see only our application output ?

**Comment by hdgarrood** [comment]
Your application won't be run during `pulp build` so I don't think it makes sense to add a `--silent` option there. Regarding `pulp run`, does it solve this issue if you do something like `pulp build --to app.js && node app.js`?

**Comment by jgoux** [comment]
I plan to use the command along with `--watch`, isn't bundling the whole app at every change slower than just compiling ?
Right now this is what I have : 
```
  "scripts": {
    "start": "node -r dotenv/config output/index.js",
    "build": "pulp build --to output/index.js",
    "watch": "nodemon -q -w src -e js,purs --exec 'yarn build && clear && yarn start'"
  }
```
This kind of work but it's hacky.
Ideally having something like `pulp run --silent/quiet --watch --before clear` would be better.

Not directly related to this, but is there a way to pass arguments to `node` through `pulp` ? As you can see in my example I use the package `dotenv` to load my environment variables from a `.env` file before running my code.

**Comment by hdgarrood** [comment]
Ah right, yes, it will be slightly faster to skip the bundling (as `pulp run` does). I'm not sure it's a good idea to suppress everything other than your app's output in a workflow like that though. What happens if there's a compile error?

**Comment by hdgarrood** [comment]
Also I think `pulp run -- foo bar` should pass `foo bar` to your program.

**Comment by jgoux** [comment]
Sorry, I explained badly!
I totally want the compile errors, what I want to silent are the messages : 
```
* Building project in ....
* Build successful.
```
Passing the `-r dotenv/config` with `--` doesn't work because I need to pass it to `node` itself, it's not a part of my app parameters.

The `r` option in node is a hook to `require` libs outside of the executed program, it's perfect for environment configuration! :)

**Comment by hdgarrood** [comment]
Hm, sorry, I don't think this is important enough to justify adding an option, really. Two lines for each time your project gets rebuilt isn't really very much, is it?

**Comment by jgoux** [comment]
Yes it was purely esthetic. No problem!
