### ISSUE TITLE
Install on Arch Linux: Wrong binary name, Invalid option `-o'

### ISSUE THREAD

**Issue by mbid** [purescript-contrib/pulp#267]
I'm trying to setup the purescript toolchain on arch linux. I installed purescript, pulp and bower via npm
```
> npm -g purescript pulp bower
  [...]
  ⚠ The `/home/mbid/.npm-packages/lib/node_modules/purescript/vendor/psc` binary doesn't seem to work correctly
  ⚠ psc pre-build test failed
  ℹ compiling from source
```
which takes a while, but does not report any errors. Instead of a `psc` executable, however, there is only `purs` in npm's bin path. I guess this is an issue of the compiler npm package? Not surprisingly,

```
> pulp init
* ERROR: `psc` executable not found.
```
so I symlinked to npm's `purs` as `psc` from one of my directories in `$PATH`. Now `pulp init` works, but
```
> pulp build
* Building project in <some path>
Invalid option `-o'

Usage: purs COMMAND
  The PureScript compiler and tools
* ERROR: Subcommand terminated with exit code 1
```
What's going on here? I also tried installing purescript and pulp from the official arch linux repository. I had to symlink psc to purs again and then got the same error.

**Comment by natefaubion** [comment]
Please see this comment https://github.com/bodil/pulp/issues/264#issuecomment-290102078

**Comment by hdgarrood** [comment]
We pushed out the newest version of the compiler, 0.11.1, to NPM too early i.e. before other tools such as pulp work with it. If you uninstall and reinstall purescript you should now get 0.10.7 which should work nicely with everything else.

**Comment by paf31** [comment]
If you want to use Pulp with the latest compiler, you need to make a wrapper script, like the ones in `scripts/` in this repo. That's the setup I'm using right now.
