### ISSUE TITLE
pulp repl is unusable as of version 11

### ISSUE THREAD

**Issue by paf31** [purescript-contrib/pulp#273]
Since updating to Pulp 11, I don't seem to be able to type anything into psci after starting it using Pulp. Did anything change to do with the way the process gets run?

**Comment by hdgarrood** [comment]
Not as far as I can tell, aside from changing `psci` to `purs repl`. What version of Node are you using?

**Comment by paf31** [comment]
```
node --version
v5.10.1
```

It's ancient, that's probably why, thanks.
