### ISSUE TITLE
Support browserify options

### ISSUE THREAD

**Issue by coot** [purescript-contrib/pulp#274]
It would be nice to support browserify options, after double dash.  This is what I actually need:
```
pulp browserify -I test -m Test.Main -- -i "react/addons" -i 'react/lib/ReactContext' -i 'react/lib/ExecutionEnvironment'
```

**Comment by hdgarrood** [comment]
Since those options are currently sent to `purs bundle`, I don't see a good way of doing this. I think at this point it might be better to say you should run something like the following?
```
$ pulp build -I test -m Test.Main
$ browserify output/Test.Main/index.js -i react/addons [...]
```

**Comment by coot** [comment]
Yes, that's basically what I am doing. I opened an issue for that in [purescript repo](https://github.com/purescript/purescript/issues/2823).

**Comment by hdgarrood** [comment]
Yeah, sorry, that's not what I meant, it's not a purescript issue. The issue is, do we send extra arguments to `browserify` or `purs bundle`? We can't send arguments to both, and I'd rather not make a breaking change like this unless there's a very good reason.

**Comment by natefaubion** [comment]
One possibility is to prefix options with `--browserify-*`.
```
pulp bundle -I test -m Test.Main -- --browserify-i react/addons
```

**Comment by hdgarrood** [comment]
At that point I'm not sure we're really gaining very much over letting people use browserify directly though, are we?

**Comment by natefaubion** [comment]
It was a suggestion for "We can't send arguments to both" in a non-breaking manner. Whether or not it's better than just splitting out the commands is a different thing 😛

**Comment by hdgarrood** [comment]
Right, yeah, sure. I think it might be best to leave it as-is really, sorry.
