### ISSUE TITLE
Bower dependencies are not installed under `bower_components`.

### ISSUE THREAD

**Issue by stevechae** [purescript-contrib/pulp#276]
With the latest versions of Bower, dependencies seem to be installed to `wwwroot/lib` by default rather than `bower_components` as `pulp` tasks expect. This means that simply doing the following, as many guides suggest, would not work:

```
npm install -g pulp bower
pulp init
pulp run
```
As far as I can see the only way to make this work is if I were to create a `.bowerrc` file with the following content:

```
{
   "directory": "bower_components"
}
```
and run `bower install`.

Should `pulp` be updated to work with this new path or at least include `.bowerrc` upon `pulp init` to reconfigure this?

**Comment by stevechae** [comment]
Hmm, probably a non-issue... maybe I have a stray `.bowerrc` somewhere in recognized paths.

**Comment by hdgarrood** [comment]
Thank goodness for that, you had me worried for a second!

**Comment by odoe** [comment]
I was coming here about this same issue. The latest versions of bower no longer install to `bower_componets` by default, they install to `libs`. Should the scripts be updated to take this into account? 

I can take a crack at this, as it could be two compile scripts and a check if the directory exists to determine which to run in the `build()`

**Comment by hdgarrood** [comment]
I’d be very surprised if the default has changed. Are you absolutely sure it’s not due to your own configuration?

**Comment by odoe** [comment]
Sorry, my bad, you're right. I had a rogue `.bowerrc` at the root of my dev box. It must have been there for about a year because all this time I thought they changed it.
