### ISSUE TITLE
Pulp psci clobbers .psci command order

### ISSUE THREAD

**Issue by natefaubion** [purescript-contrib/pulp#28]
If you tack on some `import ...` commands at the end of your `.psci` file, the next time you run `pulp psci` it will redo your `:m` commands and tack them on at the end. This results in imports being first, breaking your session.

**Comment by hdgarrood** [comment]
Thanks for the report, sorry for not getting around to this. Since the .psci file is going away in 0.9, I don't think it's worth fixing this now.
