### ISSUE TITLE
Add support for multiple `--main`

### ISSUE THREAD

**Issue by coot** [purescript-contrib/pulp#280]
I have a [project](https://github.com/coot/purescript-isomorphic-react-example) where I have two entries `Jam.Server` and `Jam.App`.  To build it I have to run two commands:
`pulp build -m Jam.App -t .build/Jam.App/bundle.js` and `pulp -m Jam.Server -t .build/Jam.Server/server.js`.  But it would be much nicer to run just one command and be able to watch on changes:
`pulp -w build -m Jam.App -t .build/Jam.App/bundle.js -m Jam.Server -t .build/Jam.Server/server.js`

**Comment by hdgarrood** [comment]
How about this:

```
$ pulp --watch \
   --then 'pulp build --main Jam.App --to .build/Jam.App/bundle.js && pulp build --main Jam.Server --to .build/Jam.Server/server.js' \
  build
```

**Comment by coot** [comment]
That's solves the problem, thanks!
