### ISSUE TITLE
How do I build pulp ?

### ISSUE THREAD

**Issue by omefire** [purescript-contrib/pulp#282]
I have forked a copy of the repo locally, and I'm trying to build the project.
However, I can't seem to find any instructions on how to actually build it.

I saw a `scripts` file, that I tried to use to achieve my goals. But running: `node scripts build` results in `Error: Missing configuration: psc_build_version`

**Comment by hdgarrood** [comment]
Ah, I should add this to the README. The command you're looking for is `npm run build`.

**Comment by omefire** [comment]
Yeah, I've tried that. I get this error: 

`>> psvm use v0.11.4
/bin/sh: psvm: command not found
/Users/omefire/Projects/pulp/scripts.js:118
    throw new Error("shell command exited with: " + result.status);`

**Comment by hdgarrood** [comment]
Did you run `npm install`?

**Comment by omefire** [comment]
Ok, cool. I was missing `npm install`

**Comment by omefire** [comment]
Also, I'll issue a PR to add these instructions to the `README` file

**Comment by hdgarrood** [comment]
A good thing to do at the same time would be to add a suggestion to run `npm install` to that error message, and also a suggestion to use `npm run <script>` to the error message if a configuration variable is missing.
