### ISSUE TITLE
Pulp version suggests wrong git repo

### ISSUE THREAD

**Issue by coot** [purescript-contrib/pulp#293]
With a `bower.json` that's missing a `repository` field, it suggests:
```
There is a problem with your package, which meant that it could not be        
published.                                                                    
Details:                                                                      
  The 'repository' field is not present in your package manifest file. Without
  this information, Pursuit would not be able to generate source links in your
  package's documentation. Please add one - like this, for example:           
                                                                              
    "repository": {                                                           
      "type": "git",                                                          
      "url": "git://github.com/purescript/purescript-prelude.git"             
    }                                                                         
* ERROR: Subcommand terminated with exit code 1
```

The project already is in git, so I think pulp should pick it.

**Comment by hdgarrood** [comment]
I'm not convinced. It's very little effort to put the repository in bower.json and it's useful to users of your package. The error also gives another reason why we require this to be present: we need that information to be able to generate source links on Pursuit.

**Comment by paf31** [comment]
Maybe crossed wires here. I think @coot just wants the Git URL to be inferred from the current directory in the error message.

**Comment by coot** [comment]
Yes, indeed, I just want to suggest the correct git url.  I've been hit by this once, and @paf31 had to un-register my package from bower, since I didn't had right to do that.

**Comment by hdgarrood** [comment]
Ohh, I see. Yeah I'd happily review a PR for that. It's `purs publish` which is generating that message - you'll want to look in Language.PureScript.Publish I think.

The only potential issue is that if we look at the origin remote it could be an ssh URL, and we shouldn't suggest that as only people with push access can use those afaik.

I'll close this here because it's not a pulp issue, feel free to open one on the compiler repo though.
