### ISSUE TITLE
Prevent rebuilding when an equivalent build command is run

### ISSUE THREAD

**Issue by aztecrex** [purescript-contrib/pulp#303]
My `package.json` has this assigned to the test script: `pulp test`. The first time I run it, all the packages, including those in Bower, are listed as being built.  If I run it a second and subsequent times, no packages scroll by so I assume it is not rebuilding all those packages.

If I then run `$(npm bin)/pulp test`, all the packages are rebuilt. Subsequently running _that_ command does not rebuild them.

If I then run `pulp test` they are all rebuilt again and subsequent invocations of the command do not result in rebuild.

Simply, the sources are rebuilt whenever and only whenever I switch between the two commands.

It's not a big deal operationally but it indicates something might be wrong with the way Pulp or the compiler are detecting whether sources need rebuilding. I'd just really like to know what's going on.

I do not have Pulp installed globally so I think the same command is being used in either case. OS is OSX Sierra.

**Comment by natefaubion** [comment]
Pulp isn't doing the actual building, the PureScript compiler (`purs`) is. You probably have both a global and local compiler installed. It will recompile then if the versions differ.

**Comment by aztecrex** [comment]
That was it. Local version slightly newer than global.
