### ISSUE TITLE
publish release 12.x.x to NPM

### ISSUE THREAD

**Issue by aztecrex** [purescript-contrib/pulp#304]
None of the 12s are yet in NPM.

**Comment by nwolverson** [comment]
Version 12 is on npm, but not yet tagged `latest`, you can get it via `pulp@next`. (Not commenting on whether there's a reason for that still to be the case or not)

**Comment by hdgarrood** [comment]
I wanted to leave it for a bit but I think it's now fine to move the `latest` tag to point at 12.x. I'll do it when I get a moment.

**Comment by aztecrex** [comment]
thanks @nwolverson @hdgarrood. being really bad at GUIs, I couldn't find how to list the published versions on the site--still can't. But @12.0.1 worked from CLI so all good.

thanks again

**Comment by nwolverson** [comment]
FYI the npm cli lets you see this information, `npm info pulp` shows the dist tags and list of published versions, among other things.

**Comment by hdgarrood** [comment]
I've just updated the `latest` tag so that `npm i -g pulp` gets you 12.0.1.
