### ISSUE TITLE
Bower dependency

### ISSUE THREAD

**Issue by vc0d35** [purescript-contrib/pulp#308]
Hey all,

I am just getting started with purescript development but I noticed that `pulp` [depends on bower](https://github.com/purescript-contrib/pulp/blob/4fe7a40e6b4001bb69d09f2703409f10a6fdbb1e/src/Pulp/PackageManager.purs#L26). Problem is that, though bower is still being maintained, it [is deprecated](https://github.com/bower/bower/issues/2298). They even encourage using `yarn` from their homepage.

Considering this, I was wondering if there are any plans for pulp to move to a new js package management tool?

**Comment by paf31** [comment]
Pulp already supports `psc-package` as an alternative, but I don't think there are plans to remove support for bower any time soon.

**Comment by hdgarrood** [comment]
Bower is only deprecated in the sense that it now encourages people to use different package managers, such as npm, for new front-end projects in JS. It still works and is still a good option for PureScript. It's not without its problems, so I would like to see it be replaced, but that is going to involve a lot of work and it just hasn't happened yet.

This question is quite a bit wider than Pulp, so I think I'll close this as this issue tracker is probably not the best place to have this discussion.

**Comment by AngelMunoz** [comment]
@hdgarrood Hello, is this being tracked somewhere I wasn't able to find it

**Comment by hdgarrood** [comment]
Not as far as I'm aware. I doubt we'll replace Bower any time soon.
