### ISSUE TITLE
pulp init does not support `psc-package`

### ISSUE THREAD

**Issue by PierreR** [purescript-contrib/pulp#310]
`pulp` does not seem to support `psc-package` when issuing `pulp init --psc-package`.

**Comment by hdgarrood** [comment]
You want `pulp --psc-package init`; the `--psc-package` flag comes before the subcommand, see https://github.com/purescript-contrib/pulp#global-command-specific-and-pass-through-options

**Comment by PierreR** [comment]
Thanks for the quick feedback ;-)
