### ISSUE TITLE
`pulp browserify --standalone` unnecessarily checks the type of `main`

### ISSUE THREAD

**Issue by jkachmar** [purescript-contrib/pulp#314]
I can't seem to figure out how to apply `pulp browserify` to non-main-entry-point modules.

Currently I have a project with a single module export (i.e. `module Handler (handler) where ...`) that I'd like to expose to be called from JS.

Running 
    pulp browserify --skip-entry-point --standalone index --to index.js 
fails with the error:
    * ERROR: Entry point module (Main) not found.****

Currently, it's possible to get roughly the behavior I'm looking for with some hacky `npm` scripts and `webpack`, but it'd be nice if this was possible just through `pulp`.

cf. https://github.com/jkachmar/purescript-lambda-demo/blob/master/package.json#L5-L7

**Comment by hdgarrood** [comment]
Try adding `--main Handler`, i.e. `pulp browserify --main Handler --skip-entry-point --standalone index --to index.js`.

**Comment by jkachmar** [comment]
Fails with the following error:
```
* Handler cannot be used as an entry point module because it
* does not export a `main` value.
* 
* If you need to create a JavaScript bundle without an entry point, use
* the --skip-entry-point flag.
* 
* ERROR: Failed entry point check for module Handler
```

**Comment by hdgarrood** [comment]
What was the exact command you used when you got that error?

**Comment by jkachmar** [comment]
The same one you gave as an example above:
```
pulp browserify --main Handler --skip-entry-point --standalone index --to index.js
```
For reference, here are the PureScript dependencies I'm working against:
```
    "psc-package": "^0.2.5",
    "pulp": "^12.0.1",
    "purescript": "^0.11.7",
```

**Comment by hdgarrood** [comment]
This seems like it might be a bug, then; the --skip-entry-point flag should prevent this check from being performed.
