### ISSUE TITLE
Create `app.js` without `pulp server`

### ISSUE THREAD

**Issue by adius** [purescript-contrib/pulp#319]
I want to use the compiled program with `node output/app.js` as a CLI program.
The file `app.js` generated by `pulp server` works exactly like this,
but neither do the `pulp build` nor the `pulp browserify` versions.

Why is there no dedicated command to generate the `app.js` instead of having to misuse the server to build it?

**Comment by nwolverson** [comment]
`pulp run` also generates such an app wrapper (which is really just something like `require('./output/Main').main()`; but if you do `pulp build --to app.js` you also get a directly runnable bundle.

**Comment by adius** [comment]
Uhm aha, this does not seem particular intuitive or discoverable 😅

How about adding a `pulp bundle` command, which is basically `pulp build --to output/bundle.js`?

Another problem:
If I want to use it is a executable I still need to add `#! /usr/bin/env node` to the top.

Would be cool if there was a command / flag as well. Maybe `pulp bundle --executable`

**Comment by hdgarrood** [comment]
I think this is sufficiently clear in the README as well as in the output of `pulp build --help`. I don't want to add more commands which do things which are already fairly straightforward.

**Comment by adius** [comment]
I shouldn't have to read the documentation first for such an essential command.
`pulp --help` should be enough.

**Comment by adius** [comment]
And `--to` is the last command in the command options section.
They should definitely not be sorted alphabetically, but by importance.
Or there should be an additional examples section where the most important usage scenarios are described (a la https://github.com/tldr-pages/tldr)
