### ISSUE TITLE
Flag to use purescript-spec

### ISSUE THREAD

**Issue by owickstrom** [purescript-contrib/pulp#32]
Hi,

I released https://github.com/owickstrom/purescript-spec last week. Just wondering if it would be interesting to have a have a flag, e.g. `pulp init --with-spec`, to include it in the generated `Test.Main.main`? I can submit a pull request if so.

Thanks!

**Comment by bodil** [comment]
Oh, this is cool! Something I always meant to do with purescript-test-unit was to split the test runner itself off from the testing framework, so it could run any type of test without needing to know anything about the framework being used and still produce consistent and good looking output. As yours seems to produce better looking output than mine, have you considered doing something similar? That would be something I'd love to integrate into Pulp itself, but adding dependency options (and thus opinions) to pulp init isn't something I want to do.

**Comment by owickstrom** [comment]
That sounds interesting! I've only considered making the test runners separate (they are now, but I only have one :D), but not fully unaware of the test framework used. How do you think such an interface would look? I'm looking into adding support for running the same tests (purescript-spec) in a browser or phantomjs.

**Comment by bodil** [comment]
I don't know how it should look, but I guess it'll need an API for continuous reporting and be able to run both pure and async tests - and be so lightweight you hardly need any glue code. It's probably a bit of a hard problem, come to think of it. :)

**Comment by owickstrom** [comment]
Yeah, I think so as well. I'm trying to add support for async in purescript-spec now, that alone is hard! Maybe I'll cheat and look at your stuff. :)

Mvh
Oskar Wickström

**Comment by hdgarrood** [comment]
Sorry, I'm not very keen on this. Even if we had separate test runners and test frameworks, there are still quite a few core libraries (eg `maybe`, `either`, `integers`) which need tests but can't really depend on any fancy test stuff without lots of packaging gymnastics, so they use `purescript-assert` instead. And a test runner is still a dependency, even if it's lighter than a whole testing framework.

I think the current interface is perfect; super simple, and probably familiar to anyone who's written tests in almost any other language already.

Anyway I'm closing this just as housekeeping - please feel free to open new issues or add comments or whatever about this. :)

**Comment by owickstrom** [comment]
No problem, sounds reasonable to me.
