### ISSUE TITLE
Why must directory be completely clean?

### ISSUE THREAD

**Issue by adius** [purescript-contrib/pulp#320]
https://github.com/purescript-contrib/pulp/blob/b4e6ee83fed4ea12ab79b5b80cdae601366a58d6/src/Pulp/Git.purs#L29

Currently it's not even possible to run `psc-publish --manifest bower.json --resolutions resolutions.json > 1.0.0.json` because than it will create the `1.0.0.json` file and then psc-publish will complain that the directory is dirty :joy:.

At least it should allow untracked files.

**Comment by hdgarrood** [comment]
Disallowing untracked files is quite important for preventing mistakes; if an untracked file turns out to be a PureScript source file, this should definitely cause an error. You can work around this by putting the JSON file into a directory which is ignored by git, or somewhere outside the repo.

**Comment by adius** [comment]
> into a directory which is ignored by git

Oh right, this should work too. I put it outside the repo, which felt too complicated.

> Disallowing untracked files is quite important for preventing mistakes

Yeah, now that I think of it again, that's probably a good thing ...
