### ISSUE TITLE
"pulp build" fails because .psc-package/psc-0.11.7/.set/packages.json does not exist

### ISSUE THREAD

**Issue by fournilsipma** [purescript-contrib/pulp#321]
I can build my package with `psc-package build`, but `pulp --psc-package build` should work, too.

    $ pulp --psc-package build
    * Building project in /home/user/src/shop-client
    .psc-package/psc-0.11.7/.set/packages.json does not exist
    * ERROR: Subcommand terminated with exit code 1

Once `psc-package build` creates `.psc-package/psc-0.11.7/.set/packages.json`,   `pulp --psc-package build` works.

**Comment by nwolverson** [comment]
I think `psc-package build` implies `update`, but `pulp --psc-package build` does not. Not opining on whether it should, but `pulp build` does not imply `bower install` so I think it's consistent in `pulp`-land

**Comment by hdgarrood** [comment]
I don't think Pulp has enough information to be able to reliably install dependencies when they're not there, so I'd rather leave this as-is. Thanks for the suggestion, though.
