### ISSUE TITLE
can't publish with sha dependency

### ISSUE THREAD

**Issue by safareli** [purescript-contrib/pulp#322]
If I run `bower i --production && pulp build` it's all fine but if i do `pulp publish` i'm getting `Module Data.Functor.Tagged was not found.` this is part from `bower.json`
`"purescript-tagged": "LiamGoodacre/purescript-tagged#2d8367cec912e048c362f8ecd021fe06feb7b234",`

If it's not allowed to publish module with sha dependency, it would be nice if we get more informative error message for that case.

**Comment by hdgarrood** [comment]
Using sha dependencies in bower.json for packages you're wanting to publish is strongly discouraged but you should only get a warning (see https://github.com/purescript/purescript/blob/91e77b78d0b26a1b277b0aae07d892d4d2122815/src/Language/PureScript/Publish/ErrorsWarnings.hs#L348-L369). Can you provide a minimal repro case?

**Comment by hdgarrood** [comment]
This is a bug in the compiler which has now been fixed: https://github.com/purescript/purescript/issues/3061
