### ISSUE TITLE
`--include: command not found` for `pulp build`

### ISSUE THREAD

**Issue by i-am-tom** [purescript-contrib/pulp#324]
Hello!

Just something I've noticed: `include` is in the docs for `build`, but can't be used. Is this something to remove from the docs or add to the command? Either way, am happy to write the patch :)

**Comment by hdgarrood** [comment]
This has definitely worked in the past. Can you share the command you used?

**Comment by i-am-tom** [comment]
It's a "trade secrets" thing, but I'll try to make a minimal reproduction tonight. Sorry, should've done that first :flushed:

**Comment by hdgarrood** [comment]
I'm going to close this for now but please do reopen this if you're able to find a reproduction which you can share.
