### ISSUE TITLE
psc installed but running it throws an exception

### ISSUE THREAD

**Issue by GildedHonour** [purescript-contrib/pulp#327]
I have psc installed:

    $ which psc
    /bin/psc

But
```
      $ psc --version
         events.js:112
               throw er; // Unhandled 'error' event
               ^


      Error: spawn /usr/lib/node_modules/purescript/vendor/psc ENOENT
          at _errnoException (util.js:1003:13)
          at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
          at onErrorNT (internal/child_process.js:379:16)
          at process._tickCallback (internal/process/next_tick.js:152:19)
          at Function.Module.runMain (module.js:705:11)
          at startup (bootstrap_node.js:193:16)
          at bootstrap_node.js:665:3
```

The same error for "psc build"

And
```

$ ls -al /bin/psc
lrwxrwxrwx 1 root root 41  2月 15 18:27 /bin/psc -> ../lib/node_modules/purescript/bin/psc.js
```
Running it with "sudo" makes no difference

Arch Linux, x64

**Comment by nwolverson** [comment]
You have the wrong repository, there is nothing in your issue to do with `pulp`. However `psc` is the old PureScript compiler executable, the current one is `purs` which will be installed by the npm package `purescript` in relatively recent versions.

If you have issues with the npm package of purescript this is the related repo: https://github.com/purescript-contrib/node-purescript

**Comment by GildedHonour** [comment]
@nwolverson thansk
