### ISSUE TITLE
pulp version, new repo, explicit version

### ISSUE THREAD

**Issue by pvinchon** [purescript-contrib/pulp#328]
Hi,

When you run `pulp version $BUMP`, the bump argument is ignore if no current version can be found.
https://github.com/purescript-contrib/pulp/blob/8225d7be440171d41f990070feae923a7ca4b9a3/src/Pulp/BumpVersion.purs#L54
This makes perfect sense if the argument sent is `major`, `minor`, or `patch`. On the other hand, this is a bit silly if the argument is `0.0.1`, or any explicit version.

Currently, I have `yes c | pulp version $BUMP` to handle new repositories, but it feels wrong.

Is there a reason for this ?
Would you mind if I submitted a PR to allow initial explicit versions ?

**Comment by hdgarrood** [comment]
> Is there a reason for this ?

Not really; it was an oversight.

>  Would you mind if I submitted a PR to allow initial explicit versions ?

Please go ahead, although I should warn you that I probably won't be able to review it very quickly.

**Comment by pvinchon** [comment]
No worries. Will do my best.
