### ISSUE TITLE
Include test-src directories during test build

### ISSUE THREAD

**Issue by paf31** [purescript-contrib/pulp#33]
I'm going to start adding things like `Arbitrary` instances for core libraries, under `test-src` in each package. Using the command line, or `gulp` or whatever, it's possible to include files under `test-src` in the build script, but in `pulp`, everything works by convention.

I suggest the convention be extended so that the test build includes files under `bower_components/**/test-src/`.

This shouldn't affect any existing libraries.

**Comment by hdgarrood** [comment]
Now that orphan instances are disallowed, I don't think this strategy will work.

**Comment by hdgarrood** [comment]
We have the `--include` option now too which allows you to do this kind of thing - so I think this can be closed.

**Comment by paf31** [comment]
Sounds good, thanks.
