### ISSUE TITLE
name conflict with pulp/pulp

### ISSUE THREAD

**Issue by juhp** [purescript-contrib/pulp#335]
You may be aware but the package name "conflicts" with http://github.com/pulp/pulp.

Any suggestions for what to name a fedora package?

**Comment by Profpatsch** [comment]
`purescript-pulp`?

**Comment by hdgarrood** [comment]
I actually wasn't aware of that project! Anyway, I'd recommend going with @Profpatsch's suggestion as well.

**Comment by juhp** [comment]
Okay makes sense yeah
