### ISSUE TITLE
Update generated project to use Effect

### ISSUE THREAD

**Issue by LiamGoodacre** [purescript-contrib/pulp#337]
Once PureScript 0.12 is out, we should be using `Effect` not `Eff`.

So main will be something like:

```purescript
module Main where

import Prelude
import Effect (Effect)
import Effect.Console (log)

main :: Effect Unit
main = do
  log "Hello sailor!"
```

**Comment by eviefp** [comment]
Did anyone start working on this? Have a couple of days off, could give it a go.

**Comment by LiamGoodacre** [comment]
@vladciobanu that would be great, thanks.

**Comment by eviefp** [comment]
Do we want to keep the old version under a flag? Like `pulp init --with-eff` or something?

I say no since it only takes a few keystrokes to replace `Effect` with `Eff`.
