### ISSUE TITLE
Update to use new --codegen flag when producing source maps

### ISSUE THREAD

**Issue by hdgarrood** [purescript-contrib/pulp#343]
The `--source-maps` option has been replaced with `--codegen`; see https://github.com/purescript/purescript/pull/3324.

Pulp should check `purs --version` and use the correct flags in each case; I would like Pulp to continue working with the 0.11.x series for at least a month or two after the 0.12 release.

**Comment by coot** [comment]
It would be good to also add support for `--codegen corefn`.

**Comment by coot** [comment]
It already works with `pulp build -- --codegen corefn` :)

**Comment by coot** [comment]
It works with `pulp build -- --codegen corefn`, and it's even documented in `pulp build --help` :).

**Comment by hdgarrood** [comment]
Resolved by #347.
