### ISSUE TITLE
pulp version runs out of memory (fatal exception)

### ISSUE THREAD

**Issue by thomashoneyman** [purescript-contrib/pulp#351]
## Summary

I am attempting to publish a new version of the open source library [purescript-halogen-select](https://github.com/citizennet/purescript-halogen-select) to Pursuit using Pulp. When I run `pulp version` I receive an error -- `JavaScript heap out of memory`.

## Environment
- Pulp version 12.2.0
- Purs version 0.12.0 
- Node version 10.4.0
- Bower version 1.8.4

## Things attempted

- Complete uninstall / reinstall of PureScript, Pulp, Node, NPM, Bower
- Switch to LTS version of Node, 8.11
- Restart computer
- Complain to coworkers

Each ends in the same error below.

## Reproduction

```sh
git clone git@github.com:citizennet/purescript-halogen-select
cd purescript-halogen-select
bower i && pulp build
pulp version
```

or, removing the library as a possible source of error, a bare-bones Halogen project:

```sh
mkdir test-pulp && cd test-pulp
pulp init && git init
bower i --save purescript-halogen
git add . && git commit -m "test"
pulp version
```

See this error:

```sh
* Checking your package using purs publish...
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/Users/honeyman/.nvm/versions/node/v10.4.0/bin/node]
 2: node::OnFatalError(char const*, char const*) [/Users/honeyman/.nvm/versions/node/v10.4.0/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/honeyman/.nvm/versions/node/v10.4.0/bin/node]
 4: v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/honeyman/.nvm/versions/node/v10.4.0/bin/node]
 5: v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/Users/honeyman/.nvm/versions/node/v10.4.0/bin/node]
 6: v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/honeyman/.nvm/versions/node/v10.4.0/bin/node]
 7: v8::internal::Heap::AllocateRawWithRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/Users/honeyman/.nvm/versions/node/v10.4.0/bin/node]
 8: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/Users/honeyman/.nvm/versions/node/v10.4.0/bin/node]
 9: v8::internal::IncrementalStringBuilder::Extend() [/Users/honeyman/.nvm/versions/node/v10.4.0/bin/node]
10: v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [/Users/honeyman/.nvm/versions/node/v10.4.0/bin/node]

... errors continue ...

44: v8::internal::Builtin_Impl_JsonStringify(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/Users/honeyman/.nvm/versions/node/v10.4.0/bin/node]
45: 0x360f25609efd
46: 0x360f25613429
47: 0x360f25613429

<--- Last few GCs --->

[8288:0x102802400]     7570 ms: Mark-sweep 1352.9 (1458.3) -> 1352.9 (1458.3) MB, 88.0 / 0.0 ms  (average mu = 0.185, current mu = 0.144) allocation failure scavenge might not succeed
[8288:0x102802400]     7653 ms: Mark-sweep 1352.9 (1458.3) -> 1352.9 (1458.3) MB, 83.0 / 0.0 ms  (average mu = 0.105, current mu = 0.001) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x10ed78a9e589 <JSObject>
    0: builtin exit frame: stringify(this=0x10ed78a87809 <Object map = 0x10ed95c82ba1>,0x10ed2d147b31 <String[2]:   >,0x10ed81c82201 <null>,0x10ed7bfdc0e1 <Object map = 0x10ed2adf3959>,0x10ed78a87809 <Object map = 0x10ed95c82ba1>)

    1: _stringify [0x10ed2d3c9801] [/usr/local/lib/node_modules/bower/lib/renderers/JsonRenderer.js:129] [bytecode=0x10eda279c839 offset=22](this=0x10ed0f679ce1 <Json...

* ERROR: Subcommand terminated as a result of receiving SIGABRT
```

**Comment by thomashoneyman** [comment]
A colleague of mine tried to reproduce this and got a different error, but still no success:

```sh
* Checking your package using purs publish...
/Users/.../.nvm/versions/node/v8.9.3/lib/node_modules/bower/lib/node_modules/q/q.js:155
                throw e;
                ^

RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at JsonRenderer._stringify (/Users/.../.nvm/versions/node/v8.9.3/lib/node_modules/bower/lib/renderers/JsonRenderer.js:126:20)
    at JsonRenderer.end (/Users/.../.nvm/versions/node/v8.9.3/lib/node_modules/bower/lib/renderers/JsonRenderer.js:16:35)
    at Logger.<anonymous> (/Users/.../.nvm/versions/node/v8.9.3/lib/node_modules/bower/lib/bin/bower.js:100:22)
    at emitOne (events.js:116:13)
    at Logger.emit (events.js:211:7)
    at Logger.emit (/Users/.../.nvm/versions/node/v8.9.3/lib/node_modules/bower/lib/node_modules/bower-logger/lib/Logger.js:29:39)
    at /Users/.../.nvm/versions/node/v8.9.3/lib/node_modules/bower/lib/commands/index.js:45:25
    at _fulfilled (/Users/.../.nvm/versions/node/v8.9.3/lib/node_modules/bower/lib/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/.../.nvm/versions/node/v8.9.3/lib/node_modules/bower/lib/node_modules/q/q.js:863:30)
* ERROR: Subcommand terminated with exit code 1
```

I tried publishing another project (`purescript-variant` by @natefaubion) and was able to do so successfully. So perhaps this issue is unique to `purescript-halogen-select`.

**Comment by hdgarrood** [comment]
Pulp calls a command like `bower list —offline —json` during publishing. Perhaps once the dependency tree reaches a certain size it chokes? What happens if you run that command directly? Also are you doing anything like running it inside a VM with limited memory?

**Comment by thomashoneyman** [comment]
> What happens if you run that command directly? 

Running the command directly outputs a tree in the terminal, and finishes successfully. The library has few dependencies, relatively speaking (just `purescript-web*`, `control`, `transformers`, `aff`).

EDIT: Whoops, I copy/pasted without noticing the `—` vs `--`. This blows up if I run it correctly.

> Also are you doing anything like running it inside a VM with limited memory?

On a Macbook Pro, 16GB RAM, 2.3GHz processor, so I don't think this is it.

Thanks for taking a look @hdgarrood!

**Comment by foresttoney** [comment]
It might be too big.

```
bower list --offline-json | wc -c
18115883
```

Which seems reasonable given the error above.

**Comment by thomashoneyman** [comment]
That's interesting; I would assume all of these are fairly standard dependencies.

```js
{
  ...,
  "dependencies": {
    "purescript-halogen": "^4.0.0",
    "purescript-web-html": "^1.0.0",
    "purescript-aff": "^5.0.0",
    "purescript-transformers": "^4.1.0",
    "purescript-control": "^4.0.0",
    "purescript-web-uievents": "^1.0.0",
    "purescript-avar": "^3.0.0",
    "purescript-web-events": "^1.0.0"
  },
  "devDependencies": {
    "purescript-debug": "^4.0.0"
}
```

**Comment by natefaubion** [comment]
Pretty sure those are all just transitive dependencies of Halogen, as well.

**Comment by natefaubion** [comment]
> bower list --offline-json

I don't think this is a valid argument. Is it supposed to be `bower list --paths`? This just lists all the transitive dependencies I think. `bower list` on it's own prints a huge tree of the dependencies for every module.

**Comment by foresttoney** [comment]
I just ran this again without fat fingering -- it blows up with the same error message. 

```
bower list --offline --json
```

**Comment by foresttoney** [comment]
[Here is the problem](https://github.com/bower/bower/blob/master/lib/renderers/JsonRenderer.js#L129).

Bower builds a `log` object, which has our dependency tree. When they try to JSON.stringify this object, it throws `RangeError: Invalid string length` 


Here is what that representation looks like:

<img width="1296" alt="screen shot 2018-06-07 at 4 56 40 pm" src="https://user-images.githubusercontent.com/6046447/41132131-20fa5562-6a74-11e8-9e0a-10331cd102dd.png">

**Comment by thomashoneyman** [comment]
Since these are all transitive dependencies of Halogen as @natefaubion mentioned, I removed all project dependencies except for just Halogen:

https://github.com/citizennet/purescript-halogen-select/commit/64e4d0c14e59eb10b1eb3ba19688ecf9fdc8de11

```js
  "dependencies": {
    "purescript-halogen": "^4.0.0"
  }
```

However, even with just Halogen as the sole dependency of the package, I still see the same error. That doesn't appear to be the fix.

**Comment by thomashoneyman** [comment]
Here's a more reasonable reproduction:

```sh
mkdir test-pulp && cd test-pulp
pulp init && git init
bower i --save purescript-halogen
git add . && git commit -m "test"
pulp version
```

This will still cause the error.

**Comment by thomashoneyman** [comment]
The function in question which calls `bower list --offline --json` has been in Pulp since March 2017 in a commit by @natefaubion:

https://github.com/purescript-contrib/pulp/commit/660414e3600862d30dee4bce73cc435c25ddd52b#diff-1b86a19097f7ca73b2dc4981f10de062R92

Perhaps the dependency footprints have simply become larger in `0.12`, and so the same few packages show up so many times they blow up the file size. And perhaps we could adjust to `bower list --paths` instead of `bower list`, as Nate mentioned, which outputs a much smaller list.

**Comment by hdgarrood** [comment]
> The function in question which calls bower list --offline --json has been in Pulp since March 2017 in a commit by @natefaubion:

Just for context, that’s actually not new: the command `bower list --offline --json` was always called while publishing a package; that commit just marks the point where we decided to move that call into `pulp` (whereas previously it was performed by the compiler executable).

The compiler expects a “resolutions file” in a similar format to the output of this problematic bower command. We only need a very small portion of the information produced by that command though; for each dependency, if the bower.json specifies anything other than a version range for it, we need to know so that we can produce a warning about that. Otherwise, we need to know which version bower’s solver picked. If I remember correctly that’s everything. Unfortunately I’m not aware of a more sensible variant of `bower list` which produces all the information we need.

**Comment by hdgarrood** [comment]
Come to think of it, perhaps some of the OOMs we are seeing might be a result of the code in Pulp which attempts to parse that massive JSON file and extract that information from it?

**Comment by thomashoneyman** [comment]
I see. I'm not sure if you saw my edit above -- running `bower list --offline --json` *does* blow up, without anything to do with Pulp.

**Comment by hdgarrood** [comment]
Ah, right: no I didn’t. That explains it, then, I guess. Perhaps we should consider reimplementing the bits of bower we need.

**Comment by thomashoneyman** [comment]
I hope that's not the answer, but perhaps it will have to be.

Side note:

Running `bower list --offline` on Halogen v3.1.3 produces this:

```
│ │ │ │ ├── purescript-partial#1.2.1
│ │ │ │ ├─┬ purescript-st#3.0.0
│ │ │ │ │ └─┬ purescript-eff#3.2.1
│ │ │ │ │   ├─┬ purescript-monoid#3.3.0
│ │ │ │ │   │ ├─┬ purescript-control#3.3.1
│ │ │ │ │   │ │ └── purescript-prelude#3.3.0
│ │ │ │ │   │ ├─┬ purescript-invariant#3.0.0
│ │ │ │ │   │ │ └── purescript-prelude#3.3.0
│ │ │ │ │   │ └─┬ purescript-newtype#2.0.0
│ │ │ │ │   │   └── purescript-prelude#3.3.0
│ │ │ │ │   └── purescript-prelude#3.3.0
│ │ │ │ ├─┬ purescript-tailrec#3.3.0
│ │ │ │ │ ├─┬ purescript-either#3.2.0
│ │ │ │ │ │ ├─┬ purescript-foldable-traversable#3.7.1
│ │ │ │ │ │ │ ├─┬ purescript-bifunctors#3.0.0
│ │ │ │ │ │ │ │ ├─┬ purescript-control#3.3.1
│ │ │ │ │ │ │ │ │ └── purescript-prelude#3.3.0
│ │ │ │ │ │ │ │ └─┬ purescript-newtype#2.0.0
│ │ │ │ │ │ │ │   └── purescript-prelude#3.3.0
│ │ │ │ │ │ │ └─┬ purescript-maybe#3.1.0
│ │ │ │ │ │ │   ├── purescript-monoid#3.3.0
│ │ │ │ │ │ │   └── purescript-prelude#3.3.0
│ │ │ │ │ │ └── purescript-prelude#3.3.0
│ │ │ │ │ ├─┬ purescript-identity#3.1.0
│ │ │ │ │ │ └─┬ purescript-foldable-traversable#3.7.1
│ │ │ │ │ │   ├─┬ purescript-bifunctors#3.0.0
│ │ │ │ │ │   │ ├─┬ purescript-control#3.3.1
│ │ │ │ │ │   │ │ └── purescript-prelude#3.3.0
│ │ │ │ │ │   │ └─┬ purescript-newtype#2.0.0
│ │ │ │ │ │   │   └── purescript-prelude#3.3.0
│ │ │ │ │ │   └─┬ purescript-maybe#3.1.0
│ │ │ │ │ │     ├── purescript-monoid#3.3.0
│ │ │ │ │ │     └── purescript-prelude#3.3.0
│ │ │ │ │ ├── purescript-partial#1.2.1
│ │ │ │ │ └─┬ purescript-st#3.0.0
│ │ │ │ │   └─┬ purescript-eff#3.2.1
│ │ │ │ │     ├─┬ purescript-monoid#3.3.0
│ │ │ │ │     │ ├─┬ purescript-control#3.3.1
│ │ │ │ │     │ │ └── purescript-prelude#3.3.0
│ │ │ │ │     │ ├─┬ purescript-invariant#3.0.0
│ │ │ │ │     │ │ └── purescript-prelude#3.3.0
│ │ │ │ │     │ └─┬ purescript-newtype#2.0.0
│ │ │ │ │     │   └── purescript-prelude#3.3.0
│ │ │ │ │     └── purescript-prelude#3.3.0
│ │ │ │ ├─┬ purescript-tuples#4.1.0
│ │ │ │ │ ├─┬ purescript-distributive#3.0.0
│ │ │ │ │ │ └─┬ purescript-identity#3.1.0
│ │ │ │ │ │   └─┬ purescript-foldable-traversable#3.7.1
│ │ │ │ │ │     ├─┬ purescript-bifunctors#3.0.0
│ │ │ │ │ │     │ ├─┬ purescript-control#3.3.1
│ │ │ │ │ │     │ │ └── purescript-prelude#3.3.0
│ │ │ │ │ │     │ └─┬ purescript-newtype#2.0.0
│ │ │ │ │ │     │   └── purescript-prelude#3.3.0
│ │ │ │ │ │     └─┬ purescript-maybe#3.1.0
│ │ │ │ │ │       ├── purescript-monoid#3.3.0
│ │ │ │ │ │       └── purescript-prelude#3.3.0
│ │ │ │ │ ├─┬ purescript-foldable-traversable#3.7.1
│ │ │ │ │ │ ├─┬ purescript-bifunctors#3.0.0
│ │ │ │ │ │ │ ├─┬ purescript-control#3.3.1
│ │ │ │ │ │ │ │ └── purescript-prelude#3.3.0
│ │ │ │ │ │ │ └─┬ purescript-newtype#2.0.0
│ │ │ │ │ │ │   └── purescript-prelude#3.3.0
│ │ │ │ │ │ └─┬ purescript-maybe#3.1.0
│ │ │ │ │ │   ├── purescript-monoid#3.3.0
│ │ │ │ │ │   └── purescript-prelude#3.3.0
│ │ │ │ │ ├── purescript-prelude#3.3.0
│ │ │ │ │ └─┬ purescript-type-equality#2.1.0
│ │ │ │ │   └── purescript-eff#3.2.1
│ │ │ │ ├─┬ purescript-unfoldable#3.2.0
│ │ │ │ │ ├── purescript-partial#1.2.1
│ │ │ │ │ └─┬ purescript-tuples#4.1.0
│ │ │ │ │   ├─┬ purescript-distributive#3.0.0
│ │ │ │ │   │ └─┬ purescript-identity#3.1.0
│ │ │ │ │   │   └─┬ purescript-foldable-traversable#3.7.1
│ │ │ │ │   │     ├─┬ purescript-bifunctors#3.0.0
│ │ │ │ │   │     │ ├─┬ purescript-control#3.3.1
│ │ │ │ │   │     │ │ └── purescript-prelude#3.3.0
│ │ │ │ │   │     │ └─┬ purescript-newtype#2.0.0
│ │ │ │ │   │     │   └── purescript-prelude#3.3.0
│ │ │ │ │   │     └─┬ purescript-maybe#3.1.0
│ │ │ │ │   │       ├── purescript-monoid#3.3.0
│ │ │ │ │   │       └── purescript-prelude#3.3.0
│ │ │ │ │   ├─┬ purescript-foldable-traversable#3.7.1
│ │ │ │ │   │ ├─┬ purescript-bifunctors#3.0.0
│ │ │ │ │   │ │ ├─┬ purescript-control#3.3.1
│ │ │ │ │   │ │ │ └── purescript-prelude#3.3.0
│ │ │ │ │   │ │ └─┬ purescript-newtype#2.0.0
│ │ │ │ │   │ │   └── purescript-prelude#3.3.0
│ │ │ │ │   │ └─┬ purescript-maybe#3.1.0
│ │ │ │ │   │   ├── purescript-monoid#3.3.0
│ │ │ │ │   │   └── purescript-prelude#3.3.0
│ │ │ │ │   ├── purescript-prelude#3.3.0
│ │ │ │ │   └─┬ purescript-type-equality#2.1.0
│ │ │ │ │     └── purescript-eff#3.2.1
│ │ │ │ └── purescript-unsafe-coerce#3.0.0
```

Running the same on `v4.0.0` produces this, except continuing for another several thousand lines (as far as my terminal can show), and possibly tens of thousands of lines. Appears to have the same result, it's just 4.0.0 produces a _massive_ increase in output.

```
        │ │ │   ├─┬ purescript-effect#2.0.0
        │ │ │   │ └── purescript-prelude#4.0.1
        │ │ │   └── purescript-prelude#4.0.1
        │ │ ├─┬ purescript-tuples#5.0.0
        │ │ │ ├─┬ purescript-bifunctors#4.0.0
        │ │ │ │ ├─┬ purescript-newtype#3.0.0
        │ │ │ │ │ └── purescript-prelude#4.0.1
        │ │ │ │ └── purescript-prelude#4.0.1
        │ │ │ ├─┬ purescript-control#4.0.0
        │ │ │ │ └── purescript-prelude#4.0.1
        │ │ │ ├─┬ purescript-distributive#4.0.0
        │ │ │ │ ├─┬ purescript-identity#4.0.0
        │ │ │ │ │ ├─┬ purescript-control#4.0.0
        │ │ │ │ │ │ └── purescript-prelude#4.0.1
        │ │ │ │ │ ├─┬ purescript-foldable-traversable#4.0.0
        │ │ │ │ │ │ ├─┬ purescript-bifunctors#4.0.0
        │ │ │ │ │ │ │ ├─┬ purescript-newtype#3.0.0
        │ │ │ │ │ │ │ │ └── purescript-prelude#4.0.1
        │ │ │ │ │ │ │ └── purescript-prelude#4.0.1
        │ │ │ │ │ │ ├─┬ purescript-control#4.0.0
        │ │ │ │ │ │ │ └── purescript-prelude#4.0.1
        │ │ │ │ │ │ ├─┬ purescript-maybe#4.0.0
        │ │ │ │ │ │ │ ├─┬ purescript-control#4.0.0
        │ │ │ │ │ │ │ │ └── purescript-prelude#4.0.1
        │ │ │ │ │ │ │ ├─┬ purescript-invariant#4.0.0
        │ │ │ │ │ │ │ │ └── purescript-prelude#4.0.1
        │ │ │ │ │ │ │ ├─┬ purescript-newtype#3.0.0
        │ │ │ │ │ │ │ │ └── purescript-prelude#4.0.1
        │ │ │ │ │ │ │ └── purescript-prelude#4.0.1
        │ │ │ │ │ │ ├─┬ purescript-newtype#3.0.0
        │ │ │ │ │ │ │ └── purescript-prelude#4.0.1
        │ │ │ │ │ │ ├─┬ purescript-orders#4.0.0
        │ │ │ │ │ │ │ ├─┬ purescript-newtype#3.0.0
        │ │ │ │ │ │ │ │ └── purescript-prelude#4.0.1
        │ │ │ │ │ │ │ └── purescript-prelude#4.0.1
        │ │ │ │ │ │ └── purescript-prelude#4.0.1
        │ │ │ │ │ ├─┬ purescript-invariant#4.0.0
        │ │ │ │ │ │ └── purescript-prelude#4.0.1
        │ │ │ │ │ ├─┬ purescript-newtype#3.0.0
        │ │ │ │ │ │ └── purescript-prelude#4.0.1
        │ │ │ │ │ └── purescript-prelude#4.0.1
        │ │ │ │ ├─┬ purescript-newtype#3.0.0
        │ │ │ │ │ └── purescript-prelude#4.0.1
        │ │ │ │ └── purescript-prelude#4.0.1
```

It doesn't appear Bower has changed functionality from digging through their changes, either.

**Comment by thomashoneyman** [comment]
> We only need a very small portion of the information produced by that command though; for each dependency, if the bower.json specifies anything other than a version range for it, we need to know so that we can produce a warning about that. Otherwise, we need to know which version bower’s solver picked. If I remember correctly that’s everything.

I'm assuming we need to register the transitive dependencies, too -- we can't simply note `purescript-newtype#3.0.0` and call it a day; we'd need to check its dependencies in turn, too.

But perhaps we could do this with a lot less memory usage:

1. Start a hashmap to store package information
2. Look at the packages in `bower_components` and grab what version Bower's solver picked for each, stick that in the hashmap, no duplicates
3. Recover from the hashmap whatever format it is that Pulp requires for noting these

**Comment by thomashoneyman** [comment]
If there is no reason we have to use the JSON tree as output above ^^, then we could do this:

1. Traverse all of `bower_components`
2. For each folder, record the name and the resolution (`grep "tag\"\:" bower_components/purescript-reflection/.bower.json` or `grep "version\"\:" bower_components/purescript-reflection/.bower.json` for example)

This would result in a flat `package: version` list, and it would be the actual versions installed via Bower. We'd know exactly what versions were selected by the solver for every package / transitive dependency involved.

Would that suffice for what Pulp needs to know @hdgarrood?

It looks like this JSON is gzipped and and sent to Pursuit for documentation on the package; I'm not sure what Pursuit does with it. Ideally we could flatten out the tree altogether and just list exact packages and versions.

https://github.com/purescript-contrib/pulp/blob/master/src/Pulp/Publish.purs#L190

## Edit: Some information from Pursuit

This is the endpoint hit on Pursuit:
https://github.com/purescript/pursuit/blob/6bfb3c74e86e7cdb4a7a7fdeea1fe4dd840f40a3/src/Handler/Packages.hs#L101

which relies on the Bower-JSON package:
https://hackage.haskell.org/package/bower-json-1.0.0.1/docs/Web-Bower-PackageMeta.html

and calls to `verifyPackage` from PureScript:
https://github.com/purescript/purescript/blob/46a5449cb860008ff3b4048a0446415c285eef17/src/Language/PureScript/Docs/Types.hs#L76

and `parseUploadedPackage` to parse the gzipped JSON:
https://github.com/purescript/purescript/blob/46a5449cb860008ff3b4048a0446415c285eef17/src/Language/PureScript/Docs/Types.hs#L76

and eventually `asPackage`
https://github.com/purescript/purescript/blob/46a5449cb860008ff3b4048a0446415c285eef17/src/Language/PureScript/Docs/Types.hs#L489

Though all of this is a bit confusing, as it looks likes this is parsing entire package metadata whereas the resolution file would just be version numbers. So perhaps I've missed something.

**Comment by thomashoneyman** [comment]
Mistaken above. The resolutions file ends up being parsed in the compiler here:
https://github.com/purescript/purescript/blob/0798e334c7cfc22b508d54786b94d463b93ef156/src/Language/PureScript/Publish.hs#L293

It seems like we could update the compiler to just traverse the directories directly rather than rely on Bower. It could walk through and find the resolutions as a process on the filesystem.

**Comment by paluh** [comment]
@thomashoneyman Have you found any workaround for this issue?

**Comment by thomashoneyman** [comment]
Unfortunately I haven't. No Halogen-based library has made it onto Pursuit as far as I'm aware.

On the other hand, you can still publish to Bower without being affected by this bug, and therefore your libraries will still work & be available to users, it's just the docs won't make it to Pursuit.

**Comment by safareli** [comment]
I suppose one could do use --max_old_space_size

```
node --max_old_space_size=4000 ./node_modules/.bin/pulp foo bar
```

also you could add ` --trace_gc` flag to node you can see gc trace which shows amount of memory used.

**Comment by natefaubion** [comment]
@safareli The issue is apparent. The particular command used to print the resolutions yields a fully duplicated tree of transitive dependencies. When you have as much sharing among core libs as PS has, this eventually blows up. Halogen just exhibits the behavior because it has more dependencies, but it's nothing specific to Halogen. If you run the command on even small dependency sets you can see how it quickly gets out of hand.

Edit: Unless there's a bug in bower.

**Comment by safareli** [comment]
Yeah I understand that, it's just `max_old_space_size` might do the trick to publish docs before this bug gets fixed.

**Comment by paluh** [comment]
@safareli  Thanks for the hint!

I'm not proud of this as this is not a real solution, but with this fake bower (I've put it on the front of my `PATH` and locally into `./node_modules/.bin/bower`):

``` shell
#!/usr/bin/env bash
node --max-old-space-size=6024 /nix/store/vw48lam64l7r6x2081pkfkxprn1z6vzw-node-bower-1.8.4/bin/bower $@
```
I was able to publish my lib with: `pulp publish`.

P.S. I've also encountered this on my way: https://github.com/purescript/purescript/issues/3264 (and used another workaround: https://github.com/paluh/purescript-pulp-publish-problem)

**Comment by safareli** [comment]
we got similar error for purescript-web3 https://travis-ci.org/f-o-a-m/purescript-web3/builds/467918616#L2400

**Comment by hdgarrood** [comment]
> It seems like we could update the compiler to just traverse the directories directly rather than rely on Bower. It could walk through and find the resolutions as a process on the filesystem.

I'd rather not do this, as we previously expended quite a bit of effort removing the compiler's dependency on Bower. Instead I'd prefer to change the format the compiler expects for the `resolutions` file. I've opened a compiler issue: https://github.com/purescript/purescript/issues/3499

**Comment by hdgarrood** [comment]
To clarify, the course of action I'm suggesting is that we have `pulp` actually look through the filesystem and collect the resolutions data, and we then pass that information to the compiler. It would make our lives easier if we could also change the compiler so that it accepts this information using a more sensible schema than that of `bower list --offline --json` (and this is what I'm suggesting in that issue).
