### ISSUE TITLE
Source maps not working

### ISSUE THREAD

**Issue by mnn** [purescript-contrib/pulp#357]
From help it seems I am using it correctly:
```
$ npx pulp browserify -O --to dist/index.js --source-maps
* Browserifying project in /xxx
* Building project in /xxx
Invalid option `--source-maps'

Usage: purs COMMAND
  The PureScript compiler and tools
* ERROR: Subcommand terminated with exit code 1

$ npx pulp browserify --help 2>&1 | grep -E 'Command options|source-maps|Usage'
Usage: pulp [global-options] browserify [command-options]
Command options:
  --source-maps               Generate source maps

$ npx pulp -v                                                   
Pulp version 12.3.0
purs version 0.12.0 using /xxx/node_modules/.bin/purs
```

`purescript` and `pulp` packages installed today, so they should be most recent versions (one _would_ expect the packages would be compatible).
```
    "pulp": "^12.3.0",
    "purescript": "^0.12.0",
```

Without `--source-maps` it works (so there should be no issue with my setup), but, expectedly, it is not generating any source maps.

**Comment by nwolverson** [comment]
See #347, pulp needs a release

**Comment by hdgarrood** [comment]
Sorry I dropped the ball on this; I'll push one out today. @nwolverson would you like me to give you access to the npm project so you can publish releases too, if necessary?

**Comment by hdgarrood** [comment]
I've just published v12.3.1 which includes this fix. Sorry for the delay!

**Comment by nwolverson** [comment]
@hdgarrood happy to help with that if you want, honestly in this case I didn't think of this since I last got a notification...

**Comment by hdgarrood** [comment]
@nwolverson fab, thank you! You should be able to publish releases on npm now. Feel free to make releases whenever, especially if I seem inactive. :)
