### ISSUE TITLE
Link problems in generated docs

### ISSUE THREAD

**Issue by SEIAROTg** [purescript-contrib/pulp#361]
I noticed in some generated docs there are different symbols with same name. For example in [`purescript-typelevel-prelude@3.0.0/Type.Row`](https://pursuit.purescript.org/packages/purescript-typelevel-prelude/3.0.0/docs/Type.Row), there are two `Cons`, one being a class re-exported from `Prim.Row` while the other being a type from `Prim.RowList`. Both of them have the anchor `#t:Cons` which creates ambiguity. I suggest we use a different prefix for type classes, so they will be `#c:Cons` and `#t:Cons`.

Also all links to `Prim` are currently dead in that page as it's assuming `Prim` in the same package.

**Comment by hdgarrood** [comment]
These are both compiler issues, so I've created https://github.com/purescript/purescript/issues/3502 and https://github.com/purescript/purescript/issues/3504 to track them. Thanks for the report!
