### ISSUE TITLE
Ctags generation failing silently

### ISSUE THREAD

**Issue by ahansen90** [purescript-contrib/pulp#368]
When I try `pulp docs -- --format ctags`, I get the following output:

    * Generating documentation in /home/alex/ctags-test
    * Documentation generated.

However, nothing is generated, not in `generated-docs` or anywhere else. If I just run `pulp docs`, it works correctly (generating markdown files in `generated-docs`).

Commands used to test:

- `mkdir ctags-test && cd ctags-test`
- `pulp init`
- `bower install`
- `pulp docs -- --format ctags`

With this same test project, I can do `purs docs --format ctags bower_components/**/*.purs src/**/*.purs` and it will correctly output the ctags to standard output, so I don't think this is an issue with `purs`.

`pulp` version: 12.3.1, `purs` version: 0.12.2

**Comment by hdgarrood** [comment]
Yeah, the design here needs reconsidering (perhaps at the compiler level too). `pulp docs` assumes that any documentation generated by `purs docs` is written to a file, so it ignores any data which appears on stdout. As you probably realised, you’ll just need to call `purs docs` directly for now.

**Comment by hdgarrood** [comment]
@asturtz2 do you think it would be sensible if `purs docs --format [ctags|etags]` wrote to a file `[TAGS|tags]` by default instead of writing to stdout?

**Comment by hdgarrood** [comment]
Closing this as we're going to address it in the compiler.
