### ISSUE TITLE
is there a way to build only dependencies?

### ISSUE THREAD

**Issue by safareli** [purescript-contrib/pulp#382]
this is what i'm doing now (from makefile):
```makefile
compile-deps:
	$(eval TMPDIR := $(shell mktemp -t compile-deps-tmp.XXXXXXX -d))
	mkdir -p $(TMPDIR)
	pulp build --src-path $(TMPDIR) --test-path $(TMPDIR)
```

Is there any nicer way to do this? i.e. how to tell pulp to not look at `/{src,test}` by default without setting some random empty dir instead?

**Comment by hdgarrood** [comment]
I don't think so. I think if you want to do this you might as well just use `purs compile` directly.
