### ISSUE TITLE
psc-package asks for bower.json OR psc-package.json and then requires bower.json anyway

### ISSUE THREAD

**Issue by flip111** [purescript-contrib/pulp#389]
I made a new project with spago. Than i ran the following commands:

```
» pulp version
* ERROR: No bower.json or psc-package.json found in current or parent directories. Are you in a PureScript project?
```

Ok so i install `psc-package` and type `psc-package init`

Then continuing

```
» pulp version
* Checking your package using purs publish...
* ERROR: ENOENT: no such file or directory, open 'bower.json'
```

Maybe this error

> ERROR: No bower.json or psc-package.json found in current or parent directories. Are you in a PureScript project?

Can be changed to

> ERROR: No bower.json found in current or parent directories.

And in case there is no `psc-package.json` or `packages.dhall`, also add

> Are you in a PureScript project?

**Comment by hdgarrood** [comment]
Thanks for the report. This is a good suggestion, but we are likely to drop the `bower.json` requirement soonish anyway, and also I would like to deprecate pulp soon, so I think it's probably not worth fixing this here.

**Comment by flip111** [comment]
IMO dropping bower and pulp can not come soon enough. Thanks for putting work into this!
