### ISSUE TITLE
Pulp test no longer seems to work with purs 0.13.8

### ISSUE THREAD

**Issue by newlandsvalley** [purescript-contrib/pulp#392]
After the tests compile, we get the error

`
ERROR: Entry point module (Test.Main) not found.
`

Nate replied on Slack:

> This is because the internal externs format changed, and unfortunately pulp is parsing externs for a check. I recommend making an issue to see if you can get a release with that check disabled.

**Comment by hdgarrood** [comment]
Thanks for the report. I think you should be able to work around this with the `--no-check-main` flag.

**Comment by newlandsvalley** [comment]
OK - that worked.  Many thanks @hdgarrood .

**Comment by garyb** [comment]
Maybe we could make a new version that doesn't check main? I guess we'd want to make it a breaking release since it's kinda changing the functionality. I can put a PR together if that sounds reasonable.

**Comment by hdgarrood** [comment]
Yes, that would be great, thanks 😊

**Comment by ZabutonNage** [comment]
I assume this is the same issue that causes `pulp run` to fail.
`--no-check-main` helps here, too.
