### ISSUE TITLE
Versioning confusion

### ISSUE THREAD

**Issue by SMillerDev** [purescript-contrib/pulp#407]
Is this project semantically versioned? It seemed that way with earlier versions, but currently 16.0.0 is newer than 16.0.0-1 which is not really following semantic versioning and is quite confusing to people packaging pulp.

CC https://github.com/Homebrew/homebrew-core/pull/100783

**Comment by nwolverson** [comment]
Setting aside what the version number should be, it is correct per semver that `16.0.0` is newer than `16.0.0-1` - check https://semver.org/

> When major, minor, and patch are equal, a pre-release version has lower precedence than a normal version:

> Example: 1.0.0-alpha < 1.0.0.

This is often a confusing aspect of semver for sure

**Comment by SMillerDev** [comment]
Wait, that was supposed to indicate that it was a pre-release? While the grammar seems to allow it, the examples on the webpage don't really seem to support usage of numeric-only parts for pre-release identifiers.

**Comment by JordanMartinez** [comment]
If I released a `16.0.1`, would that resolve the homebrew issue?

**Comment by SMillerDev** [comment]
It would certainly end confusion about what is supposed to be the last version so that would be much appreciated

**Comment by JordanMartinez** [comment]
16.0.1 has been published.
