### ISSUE TITLE
Warnings are hidden

### ISSUE THREAD

**Issue by garyb** [purescript-contrib/pulp#52]
Pulp currently does not display any warnings that `psc` raises. This is probably because `psc` used to be rather verbose in its output, so the output was hidden except in the case of errors. I think it should be fine to pipe the output regardless now, as unless the `-v` flag is used `psc` doesn't print messages about reading/writing files, etc.

**Comment by bodil** [comment]
It should be forwarding everything `psc` prints to stderr. Do you have a use case?

**Comment by garyb** [comment]
Sure, if you `pulp build` `purescript-arrays`:

```
* Building project in C:\Users\Gary\Documents\GitHub\purescript-arrays
* Build successful.
```

If you `psc src/**/*.purs bower_components/**/*.purs --ffi src/**/*.js --ffi bower_components/**/*.js`

```
Multiple warnings:
  Warning in module Data.Maybe.Unsafe:
  Warning in value declaration fromJust:
  Warning at C:\Users\Gary\Documents\GitHub\purescript-arrays\bower_components\purescript-maybe\src\Data\Maybe\Unsafe.purs line 10, column 1 - line 11, column 1:
      Pattern could not be determined to cover all cases.
      The definition has the following uncovered cases:

      Data.Maybe.Nothing
  See https://github.com/purescript/purescript/wiki/Error-Code-NotExhaustivePattern for more information, or to contribute content related to this error.

  Warning in module Data.Array:
  Warning in value declaration nubBy:
    Pattern could not be determined to cover all cases.
    The definition has the following uncovered cases:

    Data.Maybe.Nothing
  See https://github.com/purescript/purescript/wiki/Error-Code-NotExhaustivePattern for more information, or to contribute content related to this error.

  Warning in module Data.Array:
  Warning in value declaration groupBy:
  Warning at C:\Users\Gary\Documents\GitHub\purescript-arrays\src\Data\Array.purs line 459, column 1
 - line 460, column 1:
      Pattern could not be determined to cover all cases.
      The definition has the following uncovered cases:

      Data.Maybe.Nothing
  See https://github.com/purescript/purescript/wiki/Error-Code-NotExhaustivePattern for more information, or to contribute content related to this error.
```

(Along with a bunch of "Compiling" and "Writing" messages that shouldn't be there actually, but that's being worked on).

**Comment by bodil** [comment]
Seems these are being printed to stdout, not stderr. Is this intentional? I realise `psc` won't output any code to stdout any more, but it's still a bit of a break with *nix convention.

**Comment by garyb** [comment]
I'm not sure actually! @paf31?

**Comment by garyb** [comment]
Printing warnings to stderr seems perfectly reasonable to me though, it probably isn't intentional.

**Comment by hdgarrood** [comment]
I think this was resolved by the referenced PR in the compiler. I definitely see warnings now when building with pulp.

**Comment by bodil** [comment]
Closing this, then.
