### ISSUE TITLE
"pulp release"

### ISSUE THREAD

**Issue by hdgarrood** [purescript-contrib/pulp#57]
It would be nice to be able to release a new version of a package with minimum fuss.

After our IRC discussion (http://ircbrowse.net/browse/purescript?events_page=3976 and the following two pages) I think the design currently looks a bit like:
- Run `psc-publish --dry-run`, and exit 1 if it fails (the `--dry-run` option is not implemented yet, but will be soon)
- Run `bower version` to bump the version in bower.json, commit, and tag. I think we can just pass all command line arguments supplied to `pulp` after the "release" argument straight through to `bower version`? so for example, `pulp release patch -m "Release v%s"`
- `git push && git push --tags`
- Run `psc-publish` for real to create data for Pursuit
- Upload this data to Pursuit

One unresolved problem is how we authenticate to Pursuit. We could prompt for a GitHub username and password, use these to create a GitHub token using GitHub's HTTP API, and then save that into `~/.pulp/github-api-token` or something, with mode 0600. We could also provide a way of supplying a token directly for people who don't want to enter their password.

**Comment by bodil** [comment]
I still think it might be wiser to keep the `version` and `release` commands distinct. Particularly in situations where `git push` fails for whatever reason, where you don't want to bump the version again to retry, and also just as a safety net for the user.

`npm` stores an auth token locally after requesting the user's npmjs.org credentials. It has a `login` command for this purpose, which also allows you to log in as another user by re-running it. We may want to replicate this as well.

So,
- `pulp login` generates an auth token for Pursuit.
- `pulp version` does the bump, but only if `psc-publish` doesn't object.
- `pulp publish` (or `pulp release`? I'm just following npm's lead here) publishes the package to Bower (ie. `git push`, and we might actually want to run `bower register` here too?) and Pursuit.

**Comment by hdgarrood** [comment]
Sounds good. I'll take a look at this after I've done the `--dry-run` option for `psc-publish`. Following npm's lead with the command names does seem sensible, and also I think `publish` describes the second stage better than `release` does (if we're splitting it into two stages). Also :+1: for `bower register`.

**Comment by tfausak** [comment]
:+1:

**Comment by damncabbage** [comment]
Just following up from the chat with @hdgarrood in IRC; I'm having a crack at the above.

**Comment by paf31** [comment]
:+1: I'd love to see this, since I often forget to upload docs to Pursuit right now. I'll help out if I can, but I need to get up to speed on the Pulp source first.

**Comment by tfausak** [comment]
I would love to see this too. For what it's worth, you can automatically generate documentation on Travis CI: http://taylor.fausak.me/2015/11/15/automatically-generate-purescript-documentation/
