### ISSUE TITLE
test + browserify

### ISSUE THREAD

**Issue by owickstrom** [purescript-contrib/pulp#58]
I'm working on support for running tests in the browser using https://github.com/owickstrom/purescript-spec, first off will be Karma I think. I'll just call mocha's `describe`, `it`, etc and let Karma do the heavy lifting, so nothing fancy.

It would be very nice if pulp could do what it does in `pulp browserify` but for the `tests/Main.purs` file, i.e. create a browserify bundle for the test suite. Should I create a pull request (when I get the time)? I'm thinking something like `pulp browserify --test`.

By the way, I think pulp is a great tool for purescript, keep up the good work!

**Comment by bodil** [comment]
Yes pls, that sounds like a good thing!

**Comment by owickstrom** [comment]
Great! :)

**Comment by jdegoes** [comment]
:+1:

**Comment by bodil** [comment]
Guess this is resolved now.
