### ISSUE TITLE
Stop expanding globs

### ISSUE THREAD

**Issue by hdgarrood** [purescript-contrib/pulp#59]
As of 0.7.0, psc (and the rest of the command line tools) will now interpret file globs for files which get passed on the command line. See https://github.com/purescript/purescript/issues/1152

This was added because there is a limit on command line length on windows, and if you try to compile slamdata on windows, you reach that limit. Presumably pulp will now fail to compile projects on Windows with enough files in them, too (although I haven't tested this). So perhaps pulp should stop expanding globs?

/cc @garyb

**Comment by hdgarrood** [comment]
Oh wait, sorry, I just saw #54.

**Comment by bodil** [comment]
Well, at least you reminded me to merge #54. :)
