### ISSUE TITLE
Remove -O option for browserify?

### ISSUE THREAD

**Issue by hdgarrood** [purescript-contrib/pulp#61]
I think that since psc 0.7.0, the `psc` tool has nothing to do with dead code elimination; it just writes CommonJS modules into the output directory. Additionally, `psc` no longer recognises `--module` or `--main` options; it exits immediately with an error if they are supplied.

`pulp browserify -O` calls `psc` with both `--module` and `--main`, and so I am pretty sure that with psc 0.7.x, this will always result in an immediate error from `psc` because of these unrecognised options. So perhaps we should remove the `-O` option from `pulp browserify`. If people want DCE they can use uglifyify or just `pulp build -O`.

/cc @paf31 @garyb because I am not 100% sure that the above is correct.

**Comment by garyb** [comment]
Does pulp even need the browserify option anymore? I think `psc-bundle` gives a more useful JS package as you can actually call into it, unlike the bundles produced by browserify.

I guess browserify is useful for cases where there are third party `require`'d dependencies, but is that something `pulp` should handle? If so, I think a `pulp bundle` option would be worth adding anyway, as for general use it is better. Also we should `browserify` the `psc-bundle` output rather than the generated modules, as that way it can take advantage of DCE.

**Comment by hdgarrood** [comment]
> I think a pulp bundle option would be worth adding anyway

`pulp build -O --to main.js` will currently call `psc` and then `psc-bundle`, and write the result to main.js, so that you can just `node main.js` or `<script src="main.js">` or whatever. Is this what you were thinking `pulp bundle` would do?

Come to think of it, it might be useful to have a pulp command specifically for wrapping `psc-bundle`, because there's currently no way of getting pulp to run psc-bundle without running psc first (ie `pulp build -O --skip-compile` isn't allowed). Although on second thoughts, now that psc does incremental builds, perhaps there's no need for this anyway.

**Comment by garyb** [comment]
Oh, right :smile: disregard that then. The point still stands about running `psc-bundle` before `browserify` though, as that makes `-O` worthwhile.

**Comment by bodil** [comment]
Yes, we need the browserify option, until psc-bundle handles CommonJS dependencies. :)

Currently, `pulp browserify -O` should be an error, see #47. If `psc-bundle` actually generates CommonJS output, we could change that, but iirc it doesn't?

**Comment by garyb** [comment]
Hmm, no you're right, it's not CommonJS. I've used the output [successfully with webpack](https://github.com/slamdata/purescript-halogen/blob/new-components/examples/ajax/gulpfile.js#L32-L35) though (it's including `virtual-dom` in the bundle there), I think I remember you saying you'd prefer to use webpack anyway? Maybe there's something worth looking into here for multiple reasons then.

Webpack does need some extra configuration over browserify, but a basic setup similar to how I'm running it there might suffice for pulp, as it's basically behaving the same way we use browserify, only it's taking a non-CommonJS entry point.
