### ISSUE TITLE
Bower not found, maybe because i already installed it locally?

### ISSUE THREAD

**Issue by danse** [purescript-contrib/pulp#68]
``` sh
 purescript $ pulp init
* Generating project skeleton in /Users/francesco/experiments/purescript
* ERROR: `/Users/francesco/node_modules/pulp/node_modules/.bin/bower` executable not found.
```

I experience the error above. Could it be that `bower` was not installed under `pulp` because i already have it installed globally?

**Comment by bodil** [comment]
No, that shouldn't affect local dependencies. Does the file mentioned actually exist, and is it executable?

**Comment by danse** [comment]
Nope, it does not exist. I thought that it was not installed under `pulp/node_modules/.bin`, because i already have it installed.

Perhaps i should explain a bit how my environment is set up, it might be a reason for the error. I installed Node and Npm via [Nix](http://nixos.org/nix/). Nix installs everything into independent, write-only directories:

``` sh
 purescript $ ls -l $(which npm)
lrwxr-xr-x  1 francesco  staff  66 Jan  1  1970 /Users/francesco/.nix-profile/bin/npm -> /nix/store/4s5iibl7wlbbmg96rgd9a0kv31rzkwzf-nodejs-0.10.38/bin/npm
```

Since directories are write only, how can i install Node packages? One solution is to use packages wrapped in Nix packages. I do not like this solution, it is cumbersome. So whenever i need a globally available Node command, like `bower` or `pulp`, i just change directory to my `~` and install it there. I have `~/node_modules/.bin` added to my `PATH`.

So in this case i did not actually install Bower globally, i installed it locally in the same folder where i eventually installed Pulp locally. This might be the reason why Bower was not installed under `~/node_modules/pulp/node_modules/.bin`

**Comment by danse** [comment]
One question, since i see that you already have some logic in place in order to find the right executable. Maybe using the [programmatic interface](http://bower.io/docs/api/#programmatic-api) would be easier, and more robust?

**Comment by danse** [comment]
I used this workaround:
- remove Bower
- install Pulp
- install Bower again

This way Pulp will have Bower in its `node_modules`

**Comment by cdepillabout** [comment]
I'm also running into this problem.

However, the following workaround (as mentioned in the previous post), didn't seem to work:

``` bash
$ ls
...
node_modules/
...
$ ls node_modules/.bin/
...
bower
...
pulp
...
$ ls node_modules/pulp/
args.js
bower.js
browserify.js
build.js
docs.js
exec.js
files.js
index.js
init.js
LICENSE.md
log.js
package.json
project.js
psci.js
README.md
run.js
server.js
shell.js
test
test.js
validate.js
watch.js
$ npm rm bower
...
$ npm install pulp
...
$ npm install bower
...
$ `npm bin`/pulp init --force
* Generating project skeleton in /some/path
* ERROR: `/some/path/node_modules/pulp/node_modules/.bin/bower` executable not found.
$
```

Why is `pulp` looking for `bower` in `/some/path/node_modules/pulp/node_modules/.bin/bower` and not in `/some/path/node_modules/.bin/`?

Does `pulp` just not support being installed locally?

**Comment by tfausak** [comment]
I am also having this problem. I can recreate it with the following `package.json`:

``` json
{
  "private": true,
  "engines": {
    "node": "4.2.1",
    "npm": "2.14.7"
  },
  "dependencies": {
    "bower": "1.6.5",
    "pulp": "4.4.1"
  },
  "scripts": {
    "pulp": "pulp"
  }
}
```

And this `bower.json`:

``` json
{
  "name": "pulp-issue-68"
}
```

Then run `npm install`, which works fine. When I run `npm run pulp dep install`, I get this error:

```
* ERROR: `/.../example/node_modules/pulp/node_modules/.bin/bower` executable not found.
```

**Comment by tfausak** [comment]
I think this issue is the root cause: https://github.com/npm/npm/issues/1341#issuecomment-16834036
