### ISSUE TITLE
Check dependency status before invoking psc?

### ISSUE THREAD

**Issue by hdgarrood** [purescript-contrib/pulp#69]
I often forget to `bower i` before I `pulp build`. It might be nice if pulp checked that the dependencies listed in bower.json were coherent with what is installed in `bower_components` before it invoked any of the compiler programs (`psc`, `psc-bundle`, etc).

**Comment by bodil** [comment]
I wouldn't want that to be a strict requirement, but if you're able to perform a test like that cheaply (ie. no noticeable slowdown) then I wouldn't be opposed to printing a warning message about it.

**Comment by garyb** [comment]
Yeah, I'm not sure there's a great way of doing this without writing your own check. Invoking `bower` to do anything is slow as it checks whether it needs updating periodically, and also checks versions with the registry too when doing `bower list`.

**Comment by hdgarrood** [comment]
Bower has the `--offline` flag to prevent it from doing that, `psc-publish` uses this.

**Comment by garyb** [comment]
Oh right, nice! I wish I'd known about that earlier.

**Comment by hdgarrood** [comment]
Note to self: `bower list --offline --json` seems to be what we want, but isn't amazingly fast. It takes 1.34s for me on pulp as of 10.0.0, which has quite a few purescript dependencies but not _that_ many. The output includes a `missing: true` for packages that haven't been installed.

**Comment by hdgarrood** [comment]
I'm not going to get around to this any time soon and it doesn't look as if anyone else will, so closing.
