### ISSUE TITLE
documentation for pulp dep update (and perhaps other commands passed to bower) should be clearer

### ISSUE THREAD

**Issue by tphyahoo** [purescript-contrib/pulp#70]
I was working through

purescript-book/chapter2

from github and I couldn't figure out the moral equivalent of cabal install.  Eventually I figured out (by reading the purescript book) I need to run 

```
pulp dep update
```

as a first step.  

Neither 

```
pulp dep --help 
```

nor the pulp home page (https://github.com/bodil/pulp) gives any indication that there is a 

```
pulp dep update
```

action.

The  home page does say 

```
Thus, pulp dep install foo --save is the equivalent of bower install foo --save except you don't need to install Bower globally.
```

I would add to this 

```
See pulp dep help for a listing of bower commands that can be passed to pulp.  
(Note this is pulp dep help, not pulp dep --help, which displays current text.)
```

assuming the above is true.  Maybe also some additional breadcrumbs for common usage might also be helpful such as adding that pulp dep update is a good idea, but I'm not sure where to draw the line here.

But I think at least we need a pointer that pulp  bower help.

**Comment by tphyahoo** [comment]
updated original comment to distinguish pulp dep help from pulp dep --help, to avoid confusion.

**Comment by bodil** [comment]
I just made `pulp dep --help` print Bower's help page instead, with a note about how to use it. Seemed the better solution. :)
