### ISSUE TITLE
pulp init silently overwrites existing files

### ISSUE THREAD

**Issue by zudov** [purescript-contrib/pulp#73]
To reproduce just do `pulp init` in any existing repo. Your `bower.json` and `src/Main.purs` would be overwritten.

This might end up very sad for someone. It's not just about being fool-proof, first writing something in `src/Main.purs` and only then initiating the project is quite a common scenario (at least for me).

**Comment by seanstrom** [comment]
@zudov what version of pulp are you using? Seems like there's code that protects against the scenario you described. https://github.com/bodil/pulp/blob/master/init.js#L68

**Comment by seanstrom** [comment]
I do see that pulp 4.4.0 does drop a `psc.tix` file regardless if there is a bower.json or not.
I wonder why that is...

EDIT:
The `psc.tix` ends up being related to https://github.com/purescript/purescript/issues/697

**Comment by zudov** [comment]
@seanstrom I see, my original message is quite confusing, thanks for pointing that out.

If `bower.json` exists, `pulp init` would do nothing (without --force). But if `bower.json` doesn't exists `pulp init` would create a brand new project (efficiently overwriting `src/Main.purs` and `test/Main.purs`.

**Comment by seanstrom** [comment]
@zudov ah I see what you're saying now. Hmm that would sad if I would just overwrite my files.
We probably could just check for any of those files existing before writing to them.
Or we can detect them first and stop the initialization all together. I think would prefer the latter.

@bodil thoughts?

**Comment by zudov** [comment]
@damncabbage Thanks!
