### ISSUE TITLE
Maintaining Pulp

### ISSUE THREAD

**Issue by seanstrom** [purescript-contrib/pulp#75]
Hello!
Which is the best way to help maintain Pulp?
I see Pulp is currently written in Javascript, but is also being re-written in PureScript.
Is there still a need to actively refactor/test/support the Javascript portions?
Or should I focus on helping out the PureScript re-write?

**Comment by bodil** [comment]
Currently, the JS version is actively maintained, and the PS version is something we hope to maybe get done some day - it's not close to being usable, but is expected to supersede the JS version at some point in the future. So the answer, I guess, is yes and yes, but if you want to see your patches in production any time soon I'd recommend focusing on the JS version.
