### ISSUE TITLE
Maintaining Pulp: Use Yargs for command line parsing

### ISSUE THREAD

**Issue by seanstrom** [purescript-contrib/pulp#76]
Would we be open to using [Yargs](https://github.com/bcoe/yargs) for our command line parsing logic?
Has this or any other modules been considered before for this? If so were there any issues with using them?

**Comment by bodil** [comment]
Yargs isn't able to do what the current command line parser does, and I'm not aware of any others which can. Past versions used an external package  (I forget which) but once we encountered  eg. the need to pass unrecognised arguments in certain positions on to the compiler, a custom parser became necessary. Yargs, specifically, struggles even with subcommands in my experience.
