### ISSUE TITLE
Using non-Purescript Bower dependencies?

### ISSUE THREAD

**Issue by laurencer** [purescript-contrib/pulp#86]
When including Javascript dependencies (e.g. `"dependencies": { "zm-event-kit": "^1.0.0" }`), they are not exposed to the build or test execution environments (e.g. you cannot require the module).

What is the correct way to depend on Javascript dependencies via Bower?

**Comment by bodil** [comment]
There is no correct way. The intended workflow is to install PureScript dependencies using Bower, and CommonJS dependencies using npm (which Pulp currently doesn't support directly, but `pulp browserify` will pick them up). If you have non-PS dependencies installed with Bower, you'll have to make your own arrangements to load them.
