### ISSUE TITLE
`pulp server` needs a signal handler for Ctrl-C (SIGINT)

### ISSUE THREAD

**Issue by cdepillabout** [purescript-contrib/pulp#87]
When running `pulp server` inside a docker container, it doesn't exit when pressing Ctrl-C.  According to this docker issue (https://github.com/docker/docker/pull/12228), it is caused by applications not exiting by default when they are PID 1 and receive a SIGINT.

It would be nice if `pulp` exited even when PID 1 and received a SIGINT.

**Comment by hdgarrood** [comment]
Do the docker people expect everyone to add everyone to add special handling to their programs to exit when receiving SIGINT, even when they're pid 1? That seems very strange to me.

Rather than adding code to pulp for this special case, it should be relatively easy to write a small wrapper script which does handle SIGINT in the way you want it to, right? I think I'd prefer that approach.

**Comment by cdepillabout** [comment]
I did a little more research about this.  This [blog post](https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/) outlines some of the problems and solutions.

One of the solutions it offers is to just run `pulp server` with `bash`.  `bash` has a default signal handler for SIGTERM, so it should work correctly.

So instead of doing this:

```
$ docker run -it CONTAINER_ID pulp server
```

You should do this:

```
$ docker run -it CONTAINER_ID bash -c "pulp server"
```

I guess it would be nice if pulp had a proper signal handler for SIGINT and SIGTERM, but the above does solve my problem.

**Comment by hdgarrood** [comment]
Having read the blog post you linked, the correct solution seems obvious: use their `my_init` script. As they wrote, terminating on SIGTERM isn't enough, the process running as pid 1 should also propagate SIGTERM to all its children, as well as reaping zombie processes. We certainly don't want to put that kind of stuff into `pulp server`.

**Comment by cdepillabout** [comment]
Using `my_init` would be the ideal solution, but I would have to dig through their configuration scripts to figure out how to correctly install `my_init`.  

If I was running something using `docker` in production, I would definitely look into this.  But I'm just running it to test stuff locally.  For my use-case I don't really care if zombies are reaped or SIGTERM is propagated correctly.  So running it under `bash` does work for me.

Although now that I think about it more, you make a good case that this shouldn't go into `pulp`.
