### ISSUE TITLE
Pulp discards info from Bower warnings

### ISSUE THREAD

**Issue by epost** [purescript-contrib/pulp#92]
I was getting this error:

```
erik@munin:~/dev/ex/examples-purescript/purescript-datalog-parser $ pulp build
* ERROR: Unexpected string
```

And couldn't quite figure out where it came from. It turned out to be:

```
erik@munin:/tmp/purescript-datalog-parsers $ bower install
bower EMALFORMED    Failed to read /private/tmp/purescript-datalog-parsers/bower.json

Additional error details:
Unexpected string
```

So it seems that pulp swallows crucial info in this case.

**Comment by bodil** [comment]
Are you sure? `pulp build` shouldn't be touching Bower at all.

**Comment by hdgarrood** [comment]
Yeah, I can reproduce this, on both 5.0.2 and the purescript branch.

It's the `project` stuff, https://github.com/bodil/pulp/blob/e1779ac5e56509ae8c3c9dbb7ce21af6836e0ed7/project.js#L14-L35. It's not calling bower but it is attempting to parse bower.json.

I suggest we just rethrow an error with a better message here. I'll address this in the purescript branch.
