### ISSUE TITLE
Add -j option to specify parallelism in psc

### ISSUE THREAD

**Issue by paf31** [purescript-contrib/pulp#93]
`pulp build +RTS -N4` doesn't work due to arguments being in the wrong order, but it would be nice to be able to say `pulp build -j 4`.

**Comment by bodil** [comment]
What is the right order? :)

**Comment by paf31** [comment]
`+RTS -N4` should go after all arguments to `psc`.

**Comment by paf31** [comment]
Actually, `pulp build +RTS -N4 -RTS` works, but it's a bit of a hack.

**Comment by bodil** [comment]
In other words, as long as we ensure the remainder args are put at the end of the psc command line, it should work?

Not that it matters, `-j4` is a lot nicer anyway, I'd prefer that.
